## 1. Refer the dataset "Advertising.csv" and perform following tasks.
### i) Read the dataset "Advertising.csv" in data frame.
### ii) Print first five records of dataset.
### iii) print last five records from dataset.
### iv) display the columns inside the dataset.
### v) display last three records from dataset.
### vi) display the information about the dataset and analyse the data.
### vii) display types of each columns.
### viii) check for null values in the dataset and display the sum of null values inside the column.
### ix) drop a column 'radio' from a dataset and display first ten records.
### x) increase the sales by 10% and add a new column "updated_sales" in dataframe.
### xi) display shape of data.
### xii) Find out maximum,minimum,mean,median,standard deviation value of each column.
### xiii) describe the dataset.

In [1]:
## Libraries
import pandas as pd
import numpy as np

In [13]:
#1
df = pd.read_csv('Advertising.csv')

In [4]:
#2
df.head()

      TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [6]:
#3
df.tail()

        TV  radio  newspaper  sales
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [7]:
#4
df.columns

Index(['TV', 'radio', 'newspaper', 'sales'], dtype='object')

In [8]:
#5
df.tail(3)

        TV  radio  newspaper  sales
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

In [9]:
#6
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB

In [35]:
#7
df.dtypes

TV               float64
newspaper        float64
sales            float64
updated_sales    float64
dtype: object

In [10]:
#8
df.isna().sum()

TV           0
radio        0
newspaper    0
sales        0
dtype: int64

In [14]:
#9
del df['radio']
df.head(10)

      TV  newspaper  sales
0  230.1       69.2   22.1
1   44.5       45.1   10.4
2   17.2       69.3    9.3
3  151.5       58.5   18.5
4  180.8       58.4   12.9
5    8.7       75.0    7.2
6   57.5       23.5   11.8
7  120.2       11.6   13.2
8    8.6        1.0    4.8
9  199.8       21.2   10.6

In [15]:
#10
df['updated_sales']=df['sales']*0.1+df['sales']

In [16]:
df.columns

Index(['TV', 'newspaper', 'sales', 'updated_sales'], dtype='object')

In [18]:
#11
df.shape

(200, 4)

In [34]:
#12
print("Mean: ")
print(df.describe().mean())
print("\nMedian: ")
print(df.median())
print("\nStandard deviation: ")
print(df.describe().std())
print("\nMin: ")
print(df.describe().min())
print("\nMax: ")
print(df.describe().max())

Mean:
TV               146.618342
newspaper         56.279078
sales             36.064370
updated_sales     37.170807
dtype: float64

Median:
TV               149.75
newspaper         25.75
sales             12.90
updated_sales     14.19
dtype: float64

Standard deviation:
TV               93.129307
newspaper        67.532959
sales            66.683809
updated_sales    66.333184
dtype: float64

Min:
TV               0.70
newspaper        0.30
sales            1.60
updated_sales    1.76
dtype: float64

Max:
TV               296.4
newspaper        200.0
sales            200.0
updated_sales    200.0
dtype: float64

In [26]:
#13
df.describe()

               TV   newspaper       sales  updated_sales
count  200.000000  200.000000  200.000000     200.000000
mean   147.042500   30.554000   14.022500      15.424750
std     85.854236   21.778621    5.217457       5.739202
min      0.700000    0.300000    1.600000       1.760000
25%     74.375000   12.750000   10.375000      11.412500
50%    149.750000   25.750000   12.900000      14.190000
75%    218.825000   45.100000   17.400000      19.140000
max    296.400000  114.000000   27.000000      29.700000

## 2. Refer the dataset "Salaries.csv" and perform following tasks.
### i) Read the dataset in dataframe.

### ii) display first five records.

### iii) display first ten records.

### iv) display last five records.

### v) display last ten records.

### vi) display the columns inside the dataset.

### vii) display shape of data.

### viii) describe the dataset.

### ix) display the information about the dataset and analyse the data.

### x) display types of each columns.

### xi) Find out maximum,minimum,mean,median,standard deviation value of each column.

### xii) check for null values in the dataset and display the sum of null values inside the column.

### xiii) drop all null values.

### xiv) a) display records whose salary is greater than 50000.
 ###    b) display records whose salary is less than 20000.
 ###    c) display records whose salary is between 20000 to 50000.
 ###    d) display records whose salary is greater than 100000.
 ###    e) display records whose salary is less than 100000.

### xv)  a) display records whose discipline is A.
###     b) display records whose discipline is B.
 ###    c) display records whose service is greater than 10.
###     d) display records whose service is less than 5.

### xvi) a) display records of phd and salary.
###     b) display records of rank, sex and salary.
###      c) display records without salary.
###      d) display first 50 records with rank,service and salary.
###      e) display records whose rank is Prof.
###      f) display records whose rank is AssocProf.

In [70]:
#1
df = pd.read_csv('Salaries.csv')

In [37]:
#2
df.head()

   rank discipline  phd  service   sex  salary
0  Prof          B   56       49  Male  186960
1  Prof          A   12        6  Male   93000
2  Prof          A   23       20  Male  110515
3  Prof          A   40       31  Male  131205
4  Prof          B   20       18  Male  104800

In [39]:
#3
df.head(10)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

In [40]:
#4
df.tail()

         rank discipline  phd  service     sex  salary
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [41]:
#5
df.tail(10)

         rank discipline  phd  service     sex  salary
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [42]:
#6
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [43]:
#7
df.shape

(78, 6)

In [44]:
#8
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [45]:
#9
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [47]:
#10
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [55]:
#11
df.drop(['rank','discipline','sex'],axis=1,inplace=True)
print("Mean: ")
print(df.describe().mean())
print("\nMedian: ")
print(df.median())
print("\nStandard deviation: ")
print(df.describe().std())
print("\nMin: ")
print(df.describe().min())
print("\nMax: ")
print(df.describe().max())

Mean:
phd           27.962944
service       24.586381
salary     87651.711634
dtype: float64

Median:
phd            18.5
service        14.5
salary     104671.0
dtype: float64

Standard deviation:
phd           25.987546
service       26.434201
salary     58775.610396
dtype: float64

Min:
phd         1.0
service     0.0
salary     78.0
dtype: float64

Max:
phd            78.0
service        78.0
salary     186960.0
dtype: float64

In [56]:
#12
df.isna().sum()

phd        0
service    0
salary     0
dtype: int64

In [57]:
#13
df.dropna()

    phd  service  salary
0    56       49  186960
1    12        6   93000
2    23       20  110515
3    40       31  131205
4    20       18  104800
..  ...      ...     ...
73   18       10  105450
74   19        6  104542
75   17       17  124312
76   28       14  109954
77   23       15  109646

[78 rows x 3 columns]

In [63]:
#14
#a
print(df[df.salary>50000])

    phd  service  salary
0    56       49  186960
1    12        6   93000
2    23       20  110515
3    40       31  131205
4    20       18  104800
..  ...      ...     ...
73   18       10  105450
74   19        6  104542
75   17       17  124312
76   28       14  109954
77   23       15  109646

[78 rows x 3 columns]

In [64]:
#b
print(df[df.salary<20000])

Empty DataFrame
Columns: [phd, service, salary]
Index: []

In [69]:
#c
print(df[(df.salary > 20000) & (df.salary < 50000)])

Empty DataFrame
Columns: [phd, service, salary]
Index: []

In [66]:
#d
print(df[df.salary>100000])

    phd  service  salary
0    56       49  186960
2    23       20  110515
3    40       31  131205
4    20       18  104800
5    20       20  122400
7    18       18  126300
10   39       33  128250
11   23       23  134778
13   35       33  162200
14   25       19  153750
15   17        3  150480
18   19        7  107300
19   29       27  150500
21   33       30  103106
26   38       19  148750
27   45       43  155865
29   21       20  123683
30    9        7  107008
31   22       21  155750
32   27       19  103275
33   18       18  120000
34   12        8  119800
35   28       23  126933
36   45       45  146856
37   20        8  102000
39   18       18  129000
40   39       36  137000
44   23       19  151768
45   25       25  140096
47   11       11  103613
48   17       17  111512
49   17       18  122960
51   20       14  127512
52   12        0  105000
58   36       26  144651
59   12       10  103994
61   13       10  103750
62   14        7  109650
65   36       19  117555
69   28        7  116450
72   24       15  161101
73   18       10  105450
74   19        6  104542
75   17       17  124312
76   28       14  109954
77   23       15  109646

In [65]:
#e
print(df[df.salary<100000])

    phd  service  salary
1    12        6   93000
6    20       17   81285
8    29       19   94350
9    51       51   57800
12    1        0   88000
16    8        3   75044
17    4        0   92000
20    4        4   92000
22    4        2   73000
23    2        0   85000
24   30       23   91100
25   35       31   99418
28    7        2   91300
38    4        3   91000
41   13        8   74830
42    4        2   80225
43    5        0   77000
46   11        3   74692
50   10        5   97032
53    5        3   73500
54   25       22   62884
55    2        0   72500
56   10        8   77500
57    3        1   72500
60    3        3   92000
63   29       27   91000
64   26       24   73300
66    7        6   63100
67   17       11   90450
68    4        2   77500
70    8        3   78500
71   12        9   71065

In [72]:
#15
#a
print(df[df.discipline=='A'])

         rank discipline  phd  service     sex  salary
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
32       Prof          A   27       19    Male  103275
37       Prof          A   20        8    Male  102000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
52       Prof          A   12        0  Female  105000
53   AsstProf          A    5        3  Female   73500
54  AssocProf          A   25       22  Female   62884
55   AsstProf          A    2        0  Female   72500
56  AssocProf          A   10        8  Female   77500
57   AsstProf          A    3        1  Female   72500
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
66   AsstProf          A    7        6  Female   63100
67       Prof          A   17       11  Female   90450
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [73]:
#b
print(df[df.discipline=='B'])

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
4        Prof          B   20       18    Male  104800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
20   AsstProf          B    4        4    Male   92000
25       Prof          B   35       31    Male   99418
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
50   AsstProf          B   10        5  Female   97032
51       Prof          B   20       14  Female  127512
58       Prof          B   36       26  Female  144651
59  AssocProf          B   12       10  Female  103994
60   AsstProf          B    3        3  Female   92000
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312

In [74]:
#c
print(df[df.service>10])

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
19       Prof          A   29       27    Male  150500
21       Prof          A   33       30    Male  103106
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
29       Prof          B   21       20    Male  123683
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960
51       Prof          B   20       14  Female  127512
54  AssocProf          A   25       22  Female   62884
58       Prof          B   36       26  Female  144651
63       Prof          A   29       27  Female   91000
64  AssocProf          A   26       24  Female   73300
65       Prof          A   36       19  Female  117555
67       Prof          A   17       11  Female   90450
72       Prof          B   24       15  Female  161101
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [75]:
#d
print(df[df.service<5])

        rank discipline  phd  service     sex  salary
12  AsstProf          B    1        0    Male   88000
15      Prof          B   17        3    Male  150480
16  AsstProf          B    8        3    Male   75044
17  AsstProf          B    4        0    Male   92000
20  AsstProf          B    4        4    Male   92000
22  AsstProf          A    4        2    Male   73000
23  AsstProf          A    2        0    Male   85000
28  AsstProf          B    7        2    Male   91300
38  AsstProf          B    4        3    Male   91000
42  AsstProf          B    4        2  Female   80225
43  AsstProf          B    5        0  Female   77000
46  AsstProf          B   11        3  Female   74692
52      Prof          A   12        0  Female  105000
53  AsstProf          A    5        3  Female   73500
55  AsstProf          A    2        0  Female   72500
57  AsstProf          A    3        1  Female   72500
60  AsstProf          B    3        3  Female   92000
68  AsstProf          A    4        2  Female   77500
70  AsstProf          A    8        3  Female   78500

In [82]:
#16
#a
df[['phd','salary']]

    phd  salary
0    56  186960
1    12   93000
2    23  110515
3    40  131205
4    20  104800
..  ...     ...
73   18  105450
74   19  104542
75   17  124312
76   28  109954
77   23  109646

[78 rows x 2 columns]

In [83]:
#b
df[['rank','sex','salary']]

         rank     sex  salary
0        Prof    Male  186960
1        Prof    Male   93000
2        Prof    Male  110515
3        Prof    Male  131205
4        Prof    Male  104800
..        ...     ...     ...
73       Prof  Female  105450
74  AssocProf  Female  104542
75       Prof  Female  124312
76       Prof  Female  109954
77       Prof  Female  109646

[78 rows x 3 columns]

In [85]:
#c
del df['salary']
df

         rank discipline  phd  service     sex
0        Prof          B   56       49    Male
1        Prof          A   12        6    Male
2        Prof          A   23       20    Male
3        Prof          A   40       31    Male
4        Prof          B   20       18    Male
..        ...        ...  ...      ...     ...
73       Prof          B   18       10  Female
74  AssocProf          B   19        6  Female
75       Prof          B   17       17  Female
76       Prof          A   28       14  Female
77       Prof          A   23       15  Female

[78 rows x 5 columns]

In [84]:
#d
df[['rank','service','salary']].head(50)

         rank  service  salary
0        Prof       49  186960
1        Prof        6   93000
2        Prof       20  110515
3        Prof       31  131205
4        Prof       18  104800
5        Prof       20  122400
6   AssocProf       17   81285
7        Prof       18  126300
8        Prof       19   94350
9        Prof       51   57800
10       Prof       33  128250
11       Prof       23  134778
12   AsstProf        0   88000
13       Prof       33  162200
14       Prof       19  153750
15       Prof        3  150480
16   AsstProf        3   75044
17   AsstProf        0   92000
18       Prof        7  107300
19       Prof       27  150500
20   AsstProf        4   92000
21       Prof       30  103106
22   AsstProf        2   73000
23   AsstProf        0   85000
24       Prof       23   91100
25       Prof       31   99418
26       Prof       19  148750
27       Prof       43  155865
28   AsstProf        2   91300
29       Prof       20  123683
30  AssocProf        7  107008
31       Prof       21  155750
32       Prof       19  103275
33       Prof       18  120000
34  AssocProf        8  119800
35       Prof       23  126933
36       Prof       45  146856
37       Prof        8  102000
38   AsstProf        3   91000
39       Prof       18  129000
40       Prof       36  137000
41  AssocProf        8   74830
42   AsstProf        2   80225
43   AsstProf        0   77000
44       Prof       19  151768
45       Prof       25  140096
46   AsstProf        3   74692
47  AssocProf       11  103613
48       Prof       17  111512
49       Prof       18  122960

In [79]:
#e
df[df['rank'] == 'Prof']

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   12        6    Male   93000
2   Prof          A   23       20    Male  110515
3   Prof          A   40       31    Male  131205
4   Prof          B   20       18    Male  104800
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
8   Prof          A   29       19    Male   94350
9   Prof          A   51       51    Male   57800
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
18  Prof          A   19        7    Male  107300
19  Prof          A   29       27    Male  150500
21  Prof          A   33       30    Male  103106
24  Prof          A   30       23    Male   91100
25  Prof          B   35       31    Male   99418
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
32  Prof          A   27       19    Male  103275
33  Prof          B   18       18    Male  120000
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
37  Prof          A   20        8    Male  102000
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
48  Prof          B   17       17  Female  111512
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
52  Prof          A   12        0  Female  105000
58  Prof          B   36       26  Female  144651
63  Prof          A   29       27  Female   91000
65  Prof          A   36       19  Female  117555
67  Prof          A   17       11  Female   90450
69  Prof          A   28        7  Female  116450
72  Prof          B   24       15  Female  161101
73  Prof          B   18       10  Female  105450
75  Prof          B   17       17  Female  124312
76  Prof          A   28       14  Female  109954
77  Prof          A   23       15  Female  109646

In [80]:
#f
df[df['rank'] == 'AssocProf']

         rank discipline  phd  service     sex  salary
6   AssocProf          A   20       17    Male   81285
30  AssocProf          B    9        7    Male  107008
34  AssocProf          B   12        8    Male  119800
41  AssocProf          A   13        8  Female   74830
47  AssocProf          B   11       11  Female  103613
54  AssocProf          A   25       22  Female   62884
56  AssocProf          A   10        8  Female   77500
59  AssocProf          B   12       10  Female  103994
61  AssocProf          B   13       10  Female  103750
62  AssocProf          B   14        7  Female  109650
64  AssocProf          A   26       24  Female   73300
71  AssocProf          B   12        9  Female   71065
74  AssocProf          B   19        6  Female  104542