# Que.1

In [1]:
import warnings
warnings.filterwarnings(action="ignore")

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv('iris.csv')
df.head(5)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [5]:
df.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [7]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
encoder.fit(df['species'])
df['species'] = encoder.transform(df['species'])

In [8]:
df['species'].value_counts()

species
0    50
1    50
2    50
Name: count, dtype: int64

In [9]:
df.corr()

              sepal_length  sepal_width  petal_length  petal_width   species
sepal_length      1.000000    -0.109369      0.871754     0.817954  0.782561
sepal_width      -0.109369     1.000000     -0.420516    -0.356544 -0.419446
petal_length      0.871754    -0.420516      1.000000     0.962757  0.949043
petal_width       0.817954    -0.356544      0.962757     1.000000  0.956464
species           0.782561    -0.419446      0.949043     0.956464  1.000000

In [10]:
x = df.drop(['species', 'sepal_width'], axis=1)
y = df['species']

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, train_size=0.8, random_state=123456
)

# Train model

## 1. Logistic Regression

In [13]:
from sklearn.linear_model import LogisticRegressionCV
def create_model_logistic_regression():
    model = LogisticRegressionCV()
    model.fit(x_train, y_train)
    return model

## 2. KNN

In [14]:
from sklearn.neighbors import KNeighborsClassifier
def create_knn_model():
    model = KNeighborsClassifier(n_neighbors=5)
    model.fit(x_train, y_train)
    return model

## 3. SVM

In [15]:
from sklearn.svm import SVC
def create_svm_model():
    model = SVC()
    model.fit(x_train, y_train)
    return model

## 4. Decision Tree

In [16]:
from sklearn.tree import DecisionTreeClassifier
def create_decision_tree_model():
    model = DecisionTreeClassifier(max_depth=10)
    model.fit(x_train, y_train)
    return model

## 5. Random Forest

In [17]:
from sklearn.ensemble import RandomForestClassifier
def create_random_forest_model():
    model = RandomForestClassifier(n_estimators=100, max_depth=10)
    model.fit(x_train, y_train)
    return model

## 6. AdaBoost

In [18]:
from sklearn.ensemble import AdaBoostClassifier
def create_adaboost_model():
    model = AdaBoostClassifier(n_estimators=35, learning_rate=0.2)
    model.fit(x_train, y_train)
    return model

## 7. CatBoost

In [19]:
from catboost import CatBoostClassifier
def create_catboost_model():
    model = CatBoostClassifier(learning_rate=0.2)
    model.fit(x_train, y_train)
    return model

# Model Evaluation

In [20]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
def evaluate_model_on_test_data(model):
    y_pred = model.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average="macro")
    recall = recall_score(y_test, y_pred, average="macro")
    f1 = f1_score(y_test, y_pred, average="macro")
    return f"{accuracy:.2f}", f"{precision:.2f}", f"{recall:.2f}", f"{f1:.2f}"

In [22]:
# create the models
models = []
models.append({"name": "Logistic Regression", "model": create_model_logistic_regression()})
models.append({"name": "KNN", "model": create_knn_model()})
models.append({"name": "SVM", "model": create_svm_model()})
models.append({"name": "Decision Tree", "model": create_decision_tree_model()})
models.append({"name": "Random Forest", "model": create_random_forest_model()})
models.append({"name": "AdaBoost", "model": create_adaboost_model()})
models.append({"name": "CatBoost", "model": create_catboost_model()})

0:	learn: 0.8697776	total: 143ms	remaining: 2m 22s
1:	learn: 0.7148732	total: 144ms	remaining: 1m 11s
2:	learn: 0.6052008	total: 146ms	remaining: 48.4s
3:	learn: 0.5129576	total: 147ms	remaining: 36.6s
4:	learn: 0.4447498	total: 148ms	remaining: 29.5s
5:	learn: 0.3893008	total: 150ms	remaining: 24.8s
6:	learn: 0.3410931	total: 153ms	remaining: 21.6s
7:	learn: 0.3073780	total: 154ms	remaining: 19.1s
8:	learn: 0.2828868	total: 156ms	remaining: 17.1s
9:	learn: 0.2550439	total: 157ms	remaining: 15.6s
10:	learn: 0.2386822	total: 159ms	remaining: 14.3s
11:	learn: 0.2204945	total: 160ms	remaining: 13.2s
12:	learn: 0.2048596	total: 162ms	remaining: 12.3s
13:	learn: 0.1931169	total: 163ms	remaining: 11.5s
14:	learn: 0.1759449	total: 165ms	remaining: 10.8s
15:	learn: 0.1657388	total: 166ms	remaining: 10.2s
16:	learn: 0.1559743	total: 167ms	remaining: 9.68s
17:	learn: 0.1489292	total: 169ms	remaining: 9.22s
18:	learn: 0.1411216	total: 170ms	remaining: 8.8s
19:	learn: 0.1330826	total: 172ms	remaining: 8.42s
20:	learn: 0.1272938	total: 173ms	remaining: 8.08s
21:	learn: 0.1215717	total: 175ms	remaining: 7.77s
22:	learn: 0.1154420	total: 176ms	remaining: 7.49s
23:	learn: 0.1105202	total: 178ms	remaining: 7.23s
24:	learn: 0.1051483	total: 179ms	remaining: 6.99s
25:	learn: 0.0995620	total: 181ms	remaining: 6.76s
26:	learn: 0.0959723	total: 182ms	remaining: 6.55s
27:	learn: 0.0910297	total: 184ms	remaining: 6.37s
28:	learn: 0.0880312	total: 185ms	remaining: 6.21s
29:	learn: 0.0853226	total: 187ms	remaining: 6.04s
30:	learn: 0.0829094	total: 188ms	remaining: 5.87s
31:	learn: 0.0801328	total: 189ms	remaining: 5.72s
32:	learn: 0.0776095	total: 190ms	remaining: 5.58s
33:	learn: 0.0749445	total: 192ms	remaining: 5.44s
34:	learn: 0.0722428	total: 193ms	remaining: 5.32s
35:	learn: 0.0697629	total: 194ms	remaining: 5.2s
36:	learn: 0.0680886	total: 196ms	remaining: 5.09s
37:	learn: 0.0665331	total: 197ms	remaining: 4.98s
38:	learn: 0.0648414	total: 198ms	remaining: 4.88s
39:	learn: 0.0631465	total: 199ms	remaining: 4.78s
40:	learn: 0.0613871	total: 200ms	remaining: 4.69s
41:	learn: 0.0594437	total: 202ms	remaining: 4.61s
42:	learn: 0.0580865	total: 203ms	remaining: 4.52s
43:	learn: 0.0561530	total: 204ms	remaining: 4.44s
44:	learn: 0.0547793	total: 206ms	remaining: 4.36s
45:	learn: 0.0529507	total: 207ms	remaining: 4.29s
46:	learn: 0.0510189	total: 209ms	remaining: 4.23s
47:	learn: 0.0499179	total: 210ms	remaining: 4.16s
48:	learn: 0.0489855	total: 211ms	remaining: 4.09s
49:	learn: 0.0473850	total: 212ms	remaining: 4.03s
50:	learn: 0.0465919	total: 213ms	remaining: 3.97s
51:	learn: 0.0452720	total: 214ms	remaining: 3.91s
52:	learn: 0.0442049	total: 216ms	remaining: 3.86s
53:	learn: 0.0434910	total: 217ms	remaining: 3.81s
54:	learn: 0.0428148	total: 218ms	remaining: 3.75s
55:	learn: 0.0420996	total: 220ms	remaining: 3.71s
56:	learn: 0.0407879	total: 221ms	remaining: 3.65s
57:	learn: 0.0400671	total: 222ms	remaining: 3.61s
58:	learn: 0.0394122	total: 223ms	remaining: 3.56s
59:	learn: 0.0383357	total: 224ms	remaining: 3.52s
60:	learn: 0.0376375	total: 226ms	remaining: 3.47s
61:	learn: 0.0371384	total: 227ms	remaining: 3.43s
62:	learn: 0.0366983	total: 228ms	remaining: 3.39s
63:	learn: 0.0357442	total: 229ms	remaining: 3.36s
64:	learn: 0.0351007	total: 231ms	remaining: 3.32s
65:	learn: 0.0343039	total: 232ms	remaining: 3.28s
66:	learn: 0.0337387	total: 233ms	remaining: 3.24s
67:	learn: 0.0330072	total: 234ms	remaining: 3.21s
68:	learn: 0.0324205	total: 235ms	remaining: 3.17s
69:	learn: 0.0317844	total: 236ms	remaining: 3.14s
70:	learn: 0.0312960	total: 238ms	remaining: 3.11s
71:	learn: 0.0310014	total: 239ms	remaining: 3.08s
72:	learn: 0.0304946	total: 240ms	remaining: 3.05s
73:	learn: 0.0300439	total: 241ms	remaining: 3.02s
74:	learn: 0.0295567	total: 242ms	remaining: 2.99s
75:	learn: 0.0291499	total: 244ms	remaining: 2.96s
76:	learn: 0.0285554	total: 245ms	remaining: 2.93s
77:	learn: 0.0278792	total: 246ms	remaining: 2.91s
78:	learn: 0.0274255	total: 247ms	remaining: 2.88s
79:	learn: 0.0270591	total: 248ms	remaining: 2.86s
80:	learn: 0.0267269	total: 249ms	remaining: 2.83s
81:	learn: 0.0262215	total: 251ms	remaining: 2.81s
82:	learn: 0.0259357	total: 252ms	remaining: 2.78s
83:	learn: 0.0256794	total: 253ms	remaining: 2.76s
84:	learn: 0.0251975	total: 254ms	remaining: 2.74s
85:	learn: 0.0249210	total: 256ms	remaining: 2.72s
86:	learn: 0.0245962	total: 257ms	remaining: 2.7s
87:	learn: 0.0241768	total: 258ms	remaining: 2.67s
88:	learn: 0.0237146	total: 259ms	remaining: 2.65s
89:	learn: 0.0232387	total: 261ms	remaining: 2.63s
90:	learn: 0.0229545	total: 262ms	remaining: 2.61s
91:	learn: 0.0226033	total: 263ms	remaining: 2.59s
92:	learn: 0.0222207	total: 264ms	remaining: 2.58s
93:	learn: 0.0219871	total: 265ms	remaining: 2.56s
94:	learn: 0.0216170	total: 266ms	remaining: 2.54s
95:	learn: 0.0213909	total: 267ms	remaining: 2.52s
96:	learn: 0.0211776	total: 268ms	remaining: 2.5s
97:	learn: 0.0209715	total: 270ms	remaining: 2.48s
98:	learn: 0.0207604	total: 271ms	remaining: 2.46s
99:	learn: 0.0205723	total: 272ms	remaining: 2.45s
100:	learn: 0.0203825	total: 273ms	remaining: 2.43s
101:	learn: 0.0200319	total: 274ms	remaining: 2.41s
102:	learn: 0.0198653	total: 276ms	remaining: 2.4s
103:	learn: 0.0196456	total: 277ms	remaining: 2.38s
104:	learn: 0.0193473	total: 278ms	remaining: 2.37s
105:	learn: 0.0190533	total: 280ms	remaining: 2.36s
106:	learn: 0.0187385	total: 281ms	remaining: 2.35s
107:	learn: 0.0184732	total: 282ms	remaining: 2.33s
108:	learn: 0.0182119	total: 284ms	remaining: 2.32s
109:	learn: 0.0180102	total: 285ms	remaining: 2.31s
110:	learn: 0.0178868	total: 286ms	remaining: 2.29s
111:	learn: 0.0176937	total: 288ms	remaining: 2.28s
112:	learn: 0.0174259	total: 289ms	remaining: 2.27s
113:	learn: 0.0171644	total: 290ms	remaining: 2.26s
114:	learn: 0.0169923	total: 292ms	remaining: 2.24s
115:	learn: 0.0168649	total: 293ms	remaining: 2.23s
116:	learn: 0.0167481	total: 294ms	remaining: 2.22s
117:	learn: 0.0165832	total: 295ms	remaining: 2.21s
118:	learn: 0.0164595	total: 296ms	remaining: 2.19s
119:	learn: 0.0162508	total: 297ms	remaining: 2.18s
120:	learn: 0.0160416	total: 299ms	remaining: 2.17s
121:	learn: 0.0158305	total: 300ms	remaining: 2.16s
122:	learn: 0.0156224	total: 301ms	remaining: 2.15s
123:	learn: 0.0155026	total: 303ms	remaining: 2.14s
124:	learn: 0.0153977	total: 305ms	remaining: 2.13s
125:	learn: 0.0152761	total: 306ms	remaining: 2.12s
126:	learn: 0.0151578	total: 307ms	remaining: 2.11s
127:	learn: 0.0150410	total: 309ms	remaining: 2.1s
128:	learn: 0.0149378	total: 310ms	remaining: 2.09s
129:	learn: 0.0148451	total: 311ms	remaining: 2.08s
130:	learn: 0.0146857	total: 312ms	remaining: 2.07s
131:	learn: 0.0145942	total: 314ms	remaining: 2.06s
132:	learn: 0.0144588	total: 315ms	remaining: 2.05s
133:	learn: 0.0142913	total: 316ms	remaining: 2.04s
134:	learn: 0.0142029	total: 318ms	remaining: 2.04s
135:	learn: 0.0141270	total: 319ms	remaining: 2.03s
136:	learn: 0.0140528	total: 320ms	remaining: 2.02s
137:	learn: 0.0139649	total: 321ms	remaining: 2.01s
138:	learn: 0.0138912	total: 322ms	remaining: 2s
139:	learn: 0.0137934	total: 324ms	remaining: 1.99s
140:	learn: 0.0136797	total: 326ms	remaining: 1.98s
141:	learn: 0.0135905	total: 327ms	remaining: 1.98s
142:	learn: 0.0134436	total: 329ms	remaining: 1.97s
143:	learn: 0.0133527	total: 331ms	remaining: 1.97s
144:	learn: 0.0132037	total: 332ms	remaining: 1.96s
145:	learn: 0.0131430	total: 333ms	remaining: 1.95s
146:	learn: 0.0130261	total: 335ms	remaining: 1.94s
147:	learn: 0.0129513	total: 336ms	remaining: 1.93s
148:	learn: 0.0128871	total: 337ms	remaining: 1.92s
149:	learn: 0.0127349	total: 338ms	remaining: 1.92s
150:	learn: 0.0126776	total: 340ms	remaining: 1.91s
151:	learn: 0.0125999	total: 341ms	remaining: 1.9s
152:	learn: 0.0125399	total: 343ms	remaining: 1.9s
153:	learn: 0.0124327	total: 344ms	remaining: 1.89s
154:	learn: 0.0123640	total: 345ms	remaining: 1.88s
155:	learn: 0.0122789	total: 347ms	remaining: 1.88s
156:	learn: 0.0121381	total: 348ms	remaining: 1.87s
157:	learn: 0.0120610	total: 349ms	remaining: 1.86s
158:	learn: 0.0119956	total: 351ms	remaining: 1.85s
159:	learn: 0.0119395	total: 352ms	remaining: 1.85s
160:	learn: 0.0118589	total: 354ms	remaining: 1.84s
161:	learn: 0.0117974	total: 355ms	remaining: 1.84s
162:	learn: 0.0117212	total: 356ms	remaining: 1.83s
163:	learn: 0.0116423	total: 358ms	remaining: 1.82s
164:	learn: 0.0115155	total: 359ms	remaining: 1.82s
165:	learn: 0.0114036	total: 360ms	remaining: 1.81s
166:	learn: 0.0112978	total: 362ms	remaining: 1.8s
167:	learn: 0.0112485	total: 363ms	remaining: 1.8s
168:	learn: 0.0111391	total: 365ms	remaining: 1.79s
169:	learn: 0.0110895	total: 366ms	remaining: 1.79s
170:	learn: 0.0110270	total: 368ms	remaining: 1.78s
171:	learn: 0.0109601	total: 369ms	remaining: 1.77s
172:	learn: 0.0108778	total: 370ms	remaining: 1.77s
173:	learn: 0.0107669	total: 371ms	remaining: 1.76s
174:	learn: 0.0106803	total: 373ms	remaining: 1.76s
175:	learn: 0.0105982	total: 374ms	remaining: 1.75s
176:	learn: 0.0105325	total: 375ms	remaining: 1.74s
177:	learn: 0.0104289	total: 377ms	remaining: 1.74s
178:	learn: 0.0103654	total: 378ms	remaining: 1.73s
179:	learn: 0.0102753	total: 379ms	remaining: 1.73s
180:	learn: 0.0102302	total: 381ms	remaining: 1.72s
181:	learn: 0.0101754	total: 382ms	remaining: 1.72s
182:	learn: 0.0101307	total: 384ms	remaining: 1.71s
183:	learn: 0.0100780	total: 385ms	remaining: 1.71s
184:	learn: 0.0099914	total: 387ms	remaining: 1.7s
185:	learn: 0.0099213	total: 388ms	remaining: 1.7s
186:	learn: 0.0098583	total: 389ms	remaining: 1.69s
187:	learn: 0.0097735	total: 391ms	remaining: 1.69s
188:	learn: 0.0097349	total: 393ms	remaining: 1.68s
189:	learn: 0.0096799	total: 394ms	remaining: 1.68s
190:	learn: 0.0096269	total: 395ms	remaining: 1.67s
191:	learn: 0.0095444	total: 397ms	remaining: 1.67s
192:	learn: 0.0095016	total: 398ms	remaining: 1.66s
193:	learn: 0.0094269	total: 399ms	remaining: 1.66s
194:	learn: 0.0093437	total: 401ms	remaining: 1.65s
195:	learn: 0.0092739	total: 402ms	remaining: 1.65s
196:	learn: 0.0092400	total: 403ms	remaining: 1.64s
197:	learn: 0.0092016	total: 405ms	remaining: 1.64s
198:	learn: 0.0091350	total: 406ms	remaining: 1.64s
199:	learn: 0.0090910	total: 408ms	remaining: 1.63s
200:	learn: 0.0090611	total: 409ms	remaining: 1.63s
201:	learn: 0.0090129	total: 410ms	remaining: 1.62s
202:	learn: 0.0089503	total: 412ms	remaining: 1.62s
203:	learn: 0.0089130	total: 413ms	remaining: 1.61s
204:	learn: 0.0088656	total: 414ms	remaining: 1.61s
205:	learn: 0.0088208	total: 416ms	remaining: 1.6s
206:	learn: 0.0087822	total: 417ms	remaining: 1.6s
207:	learn: 0.0087465	total: 418ms	remaining: 1.59s
208:	learn: 0.0087065	total: 420ms	remaining: 1.59s
209:	learn: 0.0086478	total: 421ms	remaining: 1.58s
210:	learn: 0.0085956	total: 422ms	remaining: 1.58s
211:	learn: 0.0085598	total: 424ms	remaining: 1.57s
212:	learn: 0.0085277	total: 425ms	remaining: 1.57s
213:	learn: 0.0084928	total: 426ms	remaining: 1.56s
214:	learn: 0.0084610	total: 427ms	remaining: 1.56s
215:	learn: 0.0084011	total: 429ms	remaining: 1.56s
216:	learn: 0.0083429	total: 430ms	remaining: 1.55s
217:	learn: 0.0083079	total: 431ms	remaining: 1.55s
218:	learn: 0.0082706	total: 432ms	remaining: 1.54s
219:	learn: 0.0082119	total: 434ms	remaining: 1.54s
220:	learn: 0.0081864	total: 435ms	remaining: 1.53s
221:	learn: 0.0081465	total: 437ms	remaining: 1.53s
222:	learn: 0.0081135	total: 438ms	remaining: 1.53s
223:	learn: 0.0080720	total: 439ms	remaining: 1.52s
224:	learn: 0.0080115	total: 441ms	remaining: 1.52s
225:	learn: 0.0079755	total: 442ms	remaining: 1.51s
226:	learn: 0.0079469	total: 443ms	remaining: 1.51s
227:	learn: 0.0079220	total: 445ms	remaining: 1.51s
228:	learn: 0.0078858	total: 446ms	remaining: 1.5s
229:	learn: 0.0078362	total: 448ms	remaining: 1.5s
230:	learn: 0.0078091	total: 449ms	remaining: 1.5s
231:	learn: 0.0077788	total: 450ms	remaining: 1.49s
232:	learn: 0.0077267	total: 452ms	remaining: 1.49s
233:	learn: 0.0077032	total: 453ms	remaining: 1.48s
234:	learn: 0.0076579	total: 455ms	remaining: 1.48s
235:	learn: 0.0076333	total: 456ms	remaining: 1.48s
236:	learn: 0.0076078	total: 458ms	remaining: 1.47s
237:	learn: 0.0075852	total: 460ms	remaining: 1.47s
238:	learn: 0.0075513	total: 461ms	remaining: 1.47s
239:	learn: 0.0075231	total: 462ms	remaining: 1.46s
240:	learn: 0.0074817	total: 464ms	remaining: 1.46s
241:	learn: 0.0074532	total: 465ms	remaining: 1.46s
242:	learn: 0.0074230	total: 466ms	remaining: 1.45s
243:	learn: 0.0073866	total: 468ms	remaining: 1.45s
244:	learn: 0.0073411	total: 469ms	remaining: 1.45s
245:	learn: 0.0073108	total: 471ms	remaining: 1.44s
246:	learn: 0.0072768	total: 472ms	remaining: 1.44s
247:	learn: 0.0072465	total: 474ms	remaining: 1.44s
248:	learn: 0.0072178	total: 475ms	remaining: 1.43s
249:	learn: 0.0071692	total: 476ms	remaining: 1.43s
250:	learn: 0.0071237	total: 478ms	remaining: 1.43s
251:	learn: 0.0070806	total: 479ms	remaining: 1.42s
252:	learn: 0.0070586	total: 480ms	remaining: 1.42s
253:	learn: 0.0070349	total: 482ms	remaining: 1.41s
254:	learn: 0.0069832	total: 483ms	remaining: 1.41s
255:	learn: 0.0069590	total: 484ms	remaining: 1.41s
256:	learn: 0.0069401	total: 486ms	remaining: 1.4s
257:	learn: 0.0069044	total: 487ms	remaining: 1.4s
258:	learn: 0.0068819	total: 488ms	remaining: 1.4s
259:	learn: 0.0068415	total: 490ms	remaining: 1.39s
260:	learn: 0.0068015	total: 491ms	remaining: 1.39s
261:	learn: 0.0067668	total: 492ms	remaining: 1.39s
262:	learn: 0.0067211	total: 494ms	remaining: 1.38s
263:	learn: 0.0066947	total: 495ms	remaining: 1.38s
264:	learn: 0.0066748	total: 496ms	remaining: 1.38s
265:	learn: 0.0066447	total: 497ms	remaining: 1.37s
266:	learn: 0.0066243	total: 499ms	remaining: 1.37s
267:	learn: 0.0065868	total: 500ms	remaining: 1.36s
268:	learn: 0.0065500	total: 501ms	remaining: 1.36s
269:	learn: 0.0065263	total: 503ms	remaining: 1.36s
270:	learn: 0.0065036	total: 505ms	remaining: 1.36s
271:	learn: 0.0064623	total: 507ms	remaining: 1.36s
272:	learn: 0.0064190	total: 508ms	remaining: 1.35s
273:	learn: 0.0063779	total: 509ms	remaining: 1.35s
274:	learn: 0.0063553	total: 511ms	remaining: 1.35s
275:	learn: 0.0063366	total: 513ms	remaining: 1.34s
276:	learn: 0.0063177	total: 515ms	remaining: 1.34s
277:	learn: 0.0062828	total: 516ms	remaining: 1.34s
278:	learn: 0.0062678	total: 517ms	remaining: 1.34s
279:	learn: 0.0062348	total: 519ms	remaining: 1.33s
280:	learn: 0.0062034	total: 521ms	remaining: 1.33s
281:	learn: 0.0061716	total: 522ms	remaining: 1.33s
282:	learn: 0.0061541	total: 523ms	remaining: 1.32s
283:	learn: 0.0061320	total: 524ms	remaining: 1.32s
284:	learn: 0.0061015	total: 526ms	remaining: 1.32s
285:	learn: 0.0060699	total: 527ms	remaining: 1.32s
286:	learn: 0.0060540	total: 528ms	remaining: 1.31s
287:	learn: 0.0060362	total: 530ms	remaining: 1.31s
288:	learn: 0.0060181	total: 531ms	remaining: 1.31s
289:	learn: 0.0059971	total: 533ms	remaining: 1.3s
290:	learn: 0.0059776	total: 534ms	remaining: 1.3s
291:	learn: 0.0059606	total: 536ms	remaining: 1.3s
292:	learn: 0.0059364	total: 538ms	remaining: 1.3s
293:	learn: 0.0059200	total: 539ms	remaining: 1.29s
294:	learn: 0.0059014	total: 540ms	remaining: 1.29s
295:	learn: 0.0058840	total: 542ms	remaining: 1.29s
296:	learn: 0.0058674	total: 544ms	remaining: 1.29s
297:	learn: 0.0058382	total: 545ms	remaining: 1.28s
298:	learn: 0.0058252	total: 546ms	remaining: 1.28s
299:	learn: 0.0058092	total: 547ms	remaining: 1.28s
300:	learn: 0.0057919	total: 549ms	remaining: 1.27s
301:	learn: 0.0057627	total: 551ms	remaining: 1.27s
302:	learn: 0.0057447	total: 552ms	remaining: 1.27s
303:	learn: 0.0057261	total: 553ms	remaining: 1.27s
304:	learn: 0.0056940	total: 555ms	remaining: 1.26s
305:	learn: 0.0056773	total: 556ms	remaining: 1.26s
306:	learn: 0.0056611	total: 557ms	remaining: 1.26s
307:	learn: 0.0056462	total: 559ms	remaining: 1.25s
308:	learn: 0.0056191	total: 560ms	remaining: 1.25s
309:	learn: 0.0056040	total: 562ms	remaining: 1.25s
310:	learn: 0.0055737	total: 563ms	remaining: 1.25s
311:	learn: 0.0055606	total: 565ms	remaining: 1.25s
312:	learn: 0.0055345	total: 566ms	remaining: 1.24s
313:	learn: 0.0055212	total: 568ms	remaining: 1.24s
314:	learn: 0.0055065	total: 569ms	remaining: 1.24s
315:	learn: 0.0054929	total: 571ms	remaining: 1.23s
316:	learn: 0.0054813	total: 572ms	remaining: 1.23s
317:	learn: 0.0054611	total: 573ms	remaining: 1.23s
318:	learn: 0.0054491	total: 575ms	remaining: 1.23s
319:	learn: 0.0054235	total: 576ms	remaining: 1.22s
320:	learn: 0.0054070	total: 578ms	remaining: 1.22s
321:	learn: 0.0053917	total: 579ms	remaining: 1.22s
322:	learn: 0.0053627	total: 581ms	remaining: 1.22s
323:	learn: 0.0053441	total: 582ms	remaining: 1.21s
324:	learn: 0.0053317	total: 583ms	remaining: 1.21s
325:	learn: 0.0053174	total: 585ms	remaining: 1.21s
326:	learn: 0.0053004	total: 586ms	remaining: 1.21s
327:	learn: 0.0052764	total: 588ms	remaining: 1.2s
328:	learn: 0.0052660	total: 589ms	remaining: 1.2s
329:	learn: 0.0052434	total: 591ms	remaining: 1.2s
330:	learn: 0.0052198	total: 592ms	remaining: 1.2s
331:	learn: 0.0052021	total: 594ms	remaining: 1.19s
332:	learn: 0.0051917	total: 595ms	remaining: 1.19s
333:	learn: 0.0051765	total: 597ms	remaining: 1.19s
334:	learn: 0.0051635	total: 598ms	remaining: 1.19s
335:	learn: 0.0051500	total: 600ms	remaining: 1.19s
336:	learn: 0.0051342	total: 601ms	remaining: 1.18s
337:	learn: 0.0051099	total: 603ms	remaining: 1.18s
338:	learn: 0.0050926	total: 604ms	remaining: 1.18s
339:	learn: 0.0050838	total: 605ms	remaining: 1.18s
340:	learn: 0.0050657	total: 608ms	remaining: 1.17s
341:	learn: 0.0050438	total: 609ms	remaining: 1.17s
342:	learn: 0.0050231	total: 611ms	remaining: 1.17s
343:	learn: 0.0050128	total: 613ms	remaining: 1.17s
344:	learn: 0.0049908	total: 614ms	remaining: 1.17s
345:	learn: 0.0049716	total: 616ms	remaining: 1.16s
346:	learn: 0.0049539	total: 618ms	remaining: 1.16s
347:	learn: 0.0049432	total: 619ms	remaining: 1.16s
348:	learn: 0.0049294	total: 620ms	remaining: 1.16s
349:	learn: 0.0049088	total: 622ms	remaining: 1.15s
350:	learn: 0.0048921	total: 623ms	remaining: 1.15s
351:	learn: 0.0048819	total: 625ms	remaining: 1.15s
352:	learn: 0.0048586	total: 626ms	remaining: 1.15s
353:	learn: 0.0048374	total: 628ms	remaining: 1.15s
354:	learn: 0.0048278	total: 629ms	remaining: 1.14s
355:	learn: 0.0048035	total: 631ms	remaining: 1.14s
356:	learn: 0.0047895	total: 633ms	remaining: 1.14s
357:	learn: 0.0047780	total: 634ms	remaining: 1.14s
358:	learn: 0.0047679	total: 636ms	remaining: 1.14s
359:	learn: 0.0047550	total: 637ms	remaining: 1.13s
360:	learn: 0.0047362	total: 639ms	remaining: 1.13s
361:	learn: 0.0047148	total: 640ms	remaining: 1.13s
362:	learn: 0.0047064	total: 642ms	remaining: 1.13s
363:	learn: 0.0046859	total: 643ms	remaining: 1.12s
364:	learn: 0.0046687	total: 645ms	remaining: 1.12s
365:	learn: 0.0046576	total: 646ms	remaining: 1.12s
366:	learn: 0.0046417	total: 648ms	remaining: 1.12s
367:	learn: 0.0046306	total: 649ms	remaining: 1.11s
368:	learn: 0.0046124	total: 651ms	remaining: 1.11s
369:	learn: 0.0045996	total: 653ms	remaining: 1.11s
370:	learn: 0.0045914	total: 654ms	remaining: 1.11s
371:	learn: 0.0045725	total: 656ms	remaining: 1.11s
372:	learn: 0.0045538	total: 657ms	remaining: 1.1s
373:	learn: 0.0045358	total: 659ms	remaining: 1.1s
374:	learn: 0.0045217	total: 661ms	remaining: 1.1s
375:	learn: 0.0045086	total: 662ms	remaining: 1.1s
376:	learn: 0.0044991	total: 664ms	remaining: 1.1s
377:	learn: 0.0044894	total: 665ms	remaining: 1.09s
378:	learn: 0.0044779	total: 667ms	remaining: 1.09s
379:	learn: 0.0044657	total: 669ms	remaining: 1.09s
380:	learn: 0.0044493	total: 670ms	remaining: 1.09s
381:	learn: 0.0044402	total: 672ms	remaining: 1.09s
382:	learn: 0.0044294	total: 673ms	remaining: 1.08s
383:	learn: 0.0044116	total: 675ms	remaining: 1.08s
384:	learn: 0.0043949	total: 677ms	remaining: 1.08s
385:	learn: 0.0043864	total: 678ms	remaining: 1.08s
386:	learn: 0.0043779	total: 680ms	remaining: 1.08s

# Summary

In [23]:
# Evaluate models
for info in models:
    accuracy,precision,recall,f1=evaluate_model_on_test_data(info["model"])
    info['accuracy']=accuracy
    info["precision"] = precision
    info["recall"] = recall
    info["f1"] = f1
    
# report
df_evaluation_report_test = pd.DataFrame(models, columns=["name", "accuracy", "precision", "recall", "f1"])
df_evaluation_report_test

                  name accuracy precision recall    f1
0  Logistic Regression     1.00      1.00   1.00  1.00
1                  KNN     1.00      1.00   1.00  1.00
2                  SVM     1.00      1.00   1.00  1.00
3        Decision Tree     0.93      0.94   0.94  0.94
4        Random Forest     0.97      0.97   0.97  0.97
5             AdaBoost     0.97      0.97   0.97  0.97
6             CatBoost     0.97      0.97   0.97  0.97

In [24]:
def visualize_model(info):
    
    y_pred = info["model"].predict(x_test)
    plt.scatter(x_test['petal_length'][y_pred == 0], x_test['petal_width'][y_pred == 0], color="green", label="setosa")
    plt.scatter(x_test['petal_length'][y_pred == 1], x_test['petal_width'][y_pred == 1], color="red", label="virsicolor")
    plt.scatter(x_test['petal_length'][y_pred == 2], x_test['petal_width'][y_pred == 2], color="orange", label="virginica")
    plt.xlabel("petal_length")
    plt.ylabel("petal_width")
    plt.title(f"{info['name']} Visualization ")
    plt.legend()

# Que 2

In [33]:
# Que.2
# The titanic.csv dataset contains information about passengers aboard the RMS Titanic, 
# including their demographic details, travel class, and fare information. 
# The dataset aims to analyze the factors that influenced passenger survival during the tragic shipwreck.
# Each record in the dataset represents one passenger with the following attributes:
# PassengerId
# Survived (0 = No, 1 = Yes)
# Pclass (Passenger class: 1st, 2nd, 3rd)
# Name
# Sex
# Age
# SibSp (Number of siblings/spouses aboard)
# Parch (Number of parents/children aboard)
# Ticket
# Fare
# Cabin
# Embarked (Port of embarkation: C, Q, S)
# Build Logistic Regression, KNN, SVM, Decision Tree, Random Forest, AdaBoost, CatBoost models to predict whether a passenger survived or not & 
# Calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.
# Also Prepare summary of all models & Select best of them.

In [124]:
df = pd.read_csv('titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [125]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [126]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [127]:
df['Age']=df['Age'].fillna(df['Age'].mean())

In [128]:
df.drop(['PassengerId','Cabin','Name','Ticket'],axis=1, inplace=True)

In [129]:
from sklearn.preprocessing import LabelEncoder
df['Embarked'] = LabelEncoder().fit_transform(df['Embarked'])
df['Sex'] = LabelEncoder().fit_transform(df['Sex'])

In [130]:
df.corr()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
Survived,1.000000,-0.338481,-0.543351,-0.069809,-0.035322,0.081629,0.257307,-0.163517
Pclass,-0.338481,1.000000,0.131900,-0.331339,0.083081,0.018443,-0.549500,0.157112
Sex,-0.543351,0.131900,1.000000,0.084153,-0.114631,-0.245489,-0.182333,0.104057
Age,-0.069809,-0.331339,0.084153,1.000000,-0.232625,-0.179191,0.091566,-0.022239
SibSp,-0.035322,0.083081,-0.114631,-0.232625,1.000000,0.414838,0.159651,0.066654
Parch,0.081629,0.018443,-0.245489,-0.179191,0.414838,1.000000,0.216225,0.038322
Fare,0.257307,-0.549500,-0.182333,0.091566,0.159651,0.216225,1.000000,-0.221226
Embarked,-0.163517,0.157112,0.104057,-0.022239,0.066654,0.038322,-0.221226,1.000000

In [131]:
df.drop(['Age','Fare'],axis=1,inplace=True)

In [132]:
x = df.drop('Survived', axis=1)
y = df['Survived']

In [133]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, train_size=0.8, random_state=123456
)

In [135]:
## 1. Logistic Regression
from sklearn.linear_model import LogisticRegressionCV
def create_model_logistic_regression():
    model = LogisticRegressionCV()
    model.fit(x_train, y_train)
    return model

In [136]:
## 2. KNN
from sklearn.neighbors import KNeighborsClassifier
def create_knn_model():
    model = KNeighborsClassifier(n_neighbors=5)
    model.fit(x_train, y_train)
    return model

In [137]:
## 3. SVM
from sklearn.svm import SVC
def create_svm_model():
    model = SVC()
    model.fit(x_train, y_train)
    return model

In [138]:
## 4. Decision Tree
from sklearn.tree import DecisionTreeClassifier
def create_decision_tree_model():
    model = DecisionTreeClassifier(max_depth=10)
    model.fit(x_train, y_train)
    return model

In [139]:
## 5. Random Forest
from sklearn.ensemble import RandomForestClassifier
def create_random_forest_model():
    model = RandomForestClassifier(n_estimators=100, max_depth=10)
    model.fit(x_train, y_train)
    return model

In [140]:
## 6. AdaBoost
from sklearn.ensemble import AdaBoostClassifier
def create_adaboost_model():
    model = AdaBoostClassifier(n_estimators=35, learning_rate=0.2)
    model.fit(x_train, y_train)
    return model

In [141]:
## 7. CatBoost
from catboost import CatBoostClassifier
def create_catboost_model():
    model = CatBoostClassifier(learning_rate=0.2)
    model.fit(x_train, y_train)
    return model

In [142]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
def evaluate_model_on_test_data(model):
    y_pred = model.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average="macro")
    recall = recall_score(y_test, y_pred, average="macro")
    f1 = f1_score(y_test, y_pred, average="macro")
    return f"{accuracy:.2f}", f"{precision:.2f}", f"{recall:.2f}", f"{f1:.2f}"

In [143]:
models = []
models.append({"name": "Logistic Regression", "model": create_model_logistic_regression()})
models.append({"name": "KNN", "model": create_knn_model()})
models.append({"name": "SVM", "model": create_svm_model()})
models.append({"name": "Decision Tree", "model": create_decision_tree_model()})
models.append({"name": "Random Forest", "model": create_random_forest_model()})
models.append({"name": "AdaBoost", "model": create_adaboost_model()})
models.append({"name": "CatBoost", "model": create_catboost_model()})

0:	learn: 0.6241142	total: 2.41ms	remaining: 2.41s
1:	learn: 0.5482092	total: 4.73ms	remaining: 2.36s
2:	learn: 0.4990876	total: 6.77ms	remaining: 2.25s
3:	learn: 0.4722088	total: 8.78ms	remaining: 2.19s
4:	learn: 0.4591696	total: 10.5ms	remaining: 2.09s
5:	learn: 0.4513580	total: 12ms	remaining: 1.99s
6:	learn: 0.4386157	total: 14.8ms	remaining: 2.1s
7:	learn: 0.4276234	total: 16.7ms	remaining: 2.08s
8:	learn: 0.4196094	total: 19.1ms	remaining: 2.1s
9:	learn: 0.4129336	total: 21.4ms	remaining: 2.12s
10:	learn: 0.4120558	total: 23.7ms	remaining: 2.13s
11:	learn: 0.4079309	total: 25.5ms	remaining: 2.1s
12:	learn: 0.4053856	total: 29.3ms	remaining: 2.22s
13:	learn: 0.4049747	total: 31.8ms	remaining: 2.24s
14:	learn: 0.4031474	total: 34.8ms	remaining: 2.28s
15:	learn: 0.4006755	total: 37.5ms	remaining: 2.31s
16:	learn: 0.3989715	total: 39.5ms	remaining: 2.29s
17:	learn: 0.3986450	total: 41.3ms	remaining: 2.25s
18:	learn: 0.3975040	total: 43.4ms	remaining: 2.24s
19:	learn: 0.3966518	total: 46.3ms	remaining: 2.27s
20:	learn: 0.3948794	total: 49.1ms	remaining: 2.29s
21:	learn: 0.3940654	total: 51.2ms	remaining: 2.28s
22:	learn: 0.3939139	total: 53ms	remaining: 2.25s
23:	learn: 0.3935181	total: 55.8ms	remaining: 2.27s
24:	learn: 0.3933593	total: 57.8ms	remaining: 2.25s
25:	learn: 0.3931874	total: 60.2ms	remaining: 2.25s
26:	learn: 0.3899176	total: 63.1ms	remaining: 2.27s
27:	learn: 0.3880837	total: 66.1ms	remaining: 2.3s
28:	learn: 0.3855147	total: 68.1ms	remaining: 2.28s
29:	learn: 0.3855124	total: 70.3ms	remaining: 2.27s
30:	learn: 0.3854637	total: 72.6ms	remaining: 2.27s
31:	learn: 0.3844002	total: 77.1ms	remaining: 2.33s
32:	learn: 0.3831761	total: 79.1ms	remaining: 2.32s
33:	learn: 0.3831137	total: 81.5ms	remaining: 2.31s
34:	learn: 0.3818391	total: 84ms	remaining: 2.32s
35:	learn: 0.3816556	total: 86.2ms	remaining: 2.31s
36:	learn: 0.3808237	total: 88.6ms	remaining: 2.31s
37:	learn: 0.3788175	total: 90.7ms	remaining: 2.3s
38:	learn: 0.3786234	total: 93ms	remaining: 2.29s
39:	learn: 0.3781494	total: 95.2ms	remaining: 2.28s
40:	learn: 0.3776547	total: 98.1ms	remaining: 2.29s
41:	learn: 0.3766911	total: 101ms	remaining: 2.3s
42:	learn: 0.3756686	total: 103ms	remaining: 2.3s
43:	learn: 0.3750003	total: 106ms	remaining: 2.3s
44:	learn: 0.3743212	total: 108ms	remaining: 2.3s
45:	learn: 0.3736414	total: 112ms	remaining: 2.31s
46:	learn: 0.3733949	total: 114ms	remaining: 2.31s
47:	learn: 0.3731641	total: 117ms	remaining: 2.32s
48:	learn: 0.3729940	total: 120ms	remaining: 2.32s
49:	learn: 0.3728519	total: 122ms	remaining: 2.31s
50:	learn: 0.3727198	total: 124ms	remaining: 2.31s
51:	learn: 0.3725825	total: 127ms	remaining: 2.31s
52:	learn: 0.3717942	total: 129ms	remaining: 2.31s
53:	learn: 0.3714820	total: 132ms	remaining: 2.31s
54:	learn: 0.3709785	total: 136ms	remaining: 2.33s
55:	learn: 0.3705762	total: 138ms	remaining: 2.33s
56:	learn: 0.3704400	total: 141ms	remaining: 2.34s
57:	learn: 0.3696365	total: 144ms	remaining: 2.34s
58:	learn: 0.3693862	total: 147ms	remaining: 2.35s
59:	learn: 0.3692401	total: 150ms	remaining: 2.35s
60:	learn: 0.3690540	total: 152ms	remaining: 2.34s
61:	learn: 0.3688392	total: 155ms	remaining: 2.35s
62:	learn: 0.3684554	total: 158ms	remaining: 2.35s
63:	learn: 0.3680961	total: 160ms	remaining: 2.34s
64:	learn: 0.3678713	total: 162ms	remaining: 2.33s
65:	learn: 0.3677907	total: 165ms	remaining: 2.33s
66:	learn: 0.3672681	total: 167ms	remaining: 2.33s
67:	learn: 0.3671505	total: 171ms	remaining: 2.34s
68:	learn: 0.3669597	total: 173ms	remaining: 2.33s
69:	learn: 0.3668613	total: 176ms	remaining: 2.34s
70:	learn: 0.3663122	total: 179ms	remaining: 2.35s
71:	learn: 0.3661692	total: 182ms	remaining: 2.34s
72:	learn: 0.3659791	total: 184ms	remaining: 2.33s
73:	learn: 0.3656921	total: 187ms	remaining: 2.34s
74:	learn: 0.3656130	total: 191ms	remaining: 2.35s
75:	learn: 0.3650515	total: 193ms	remaining: 2.35s
76:	learn: 0.3648747	total: 195ms	remaining: 2.33s
77:	learn: 0.3648390	total: 197ms	remaining: 2.33s
78:	learn: 0.3646566	total: 200ms	remaining: 2.33s
79:	learn: 0.3643694	total: 203ms	remaining: 2.33s
80:	learn: 0.3642470	total: 205ms	remaining: 2.32s
81:	learn: 0.3641122	total: 207ms	remaining: 2.32s
82:	learn: 0.3636292	total: 210ms	remaining: 2.31s
83:	learn: 0.3635652	total: 212ms	remaining: 2.31s
84:	learn: 0.3635091	total: 214ms	remaining: 2.3s
85:	learn: 0.3634760	total: 216ms	remaining: 2.29s
86:	learn: 0.3629348	total: 219ms	remaining: 2.29s
87:	learn: 0.3622251	total: 222ms	remaining: 2.3s
88:	learn: 0.3620891	total: 225ms	remaining: 2.3s
89:	learn: 0.3620624	total: 227ms	remaining: 2.3s
90:	learn: 0.3619818	total: 230ms	remaining: 2.3s
91:	learn: 0.3618145	total: 233ms	remaining: 2.3s
92:	learn: 0.3616478	total: 235ms	remaining: 2.3s
93:	learn: 0.3610944	total: 238ms	remaining: 2.29s
94:	learn: 0.3608995	total: 241ms	remaining: 2.29s
95:	learn: 0.3607671	total: 244ms	remaining: 2.29s
96:	learn: 0.3606987	total: 246ms	remaining: 2.29s
97:	learn: 0.3606808	total: 250ms	remaining: 2.3s
98:	learn: 0.3606104	total: 253ms	remaining: 2.3s
99:	learn: 0.3605258	total: 255ms	remaining: 2.3s
100:	learn: 0.3603074	total: 258ms	remaining: 2.3s
101:	learn: 0.3602434	total: 260ms	remaining: 2.29s
102:	learn: 0.3602325	total: 263ms	remaining: 2.29s
103:	learn: 0.3601798	total: 266ms	remaining: 2.29s
104:	learn: 0.3601266	total: 268ms	remaining: 2.28s
105:	learn: 0.3599852	total: 270ms	remaining: 2.28s
106:	learn: 0.3596940	total: 273ms	remaining: 2.28s
107:	learn: 0.3596426	total: 276ms	remaining: 2.28s
108:	learn: 0.3596185	total: 280ms	remaining: 2.29s
109:	learn: 0.3592355	total: 283ms	remaining: 2.29s
110:	learn: 0.3592293	total: 286ms	remaining: 2.29s
111:	learn: 0.3591290	total: 289ms	remaining: 2.29s
112:	learn: 0.3590864	total: 292ms	remaining: 2.29s
113:	learn: 0.3590162	total: 295ms	remaining: 2.29s
114:	learn: 0.3588708	total: 297ms	remaining: 2.29s
115:	learn: 0.3588114	total: 300ms	remaining: 2.29s
116:	learn: 0.3585660	total: 303ms	remaining: 2.29s
117:	learn: 0.3585385	total: 306ms	remaining: 2.29s
118:	learn: 0.3583272	total: 309ms	remaining: 2.29s
119:	learn: 0.3582078	total: 312ms	remaining: 2.29s
120:	learn: 0.3581813	total: 315ms	remaining: 2.29s
121:	learn: 0.3581440	total: 318ms	remaining: 2.29s
122:	learn: 0.3580918	total: 321ms	remaining: 2.29s
123:	learn: 0.3580496	total: 323ms	remaining: 2.29s
124:	learn: 0.3579123	total: 327ms	remaining: 2.29s
125:	learn: 0.3578347	total: 329ms	remaining: 2.28s
126:	learn: 0.3578135	total: 332ms	remaining: 2.29s
127:	learn: 0.3577698	total: 336ms	remaining: 2.29s
128:	learn: 0.3577358	total: 339ms	remaining: 2.29s
129:	learn: 0.3574590	total: 342ms	remaining: 2.29s
130:	learn: 0.3574396	total: 345ms	remaining: 2.29s
131:	learn: 0.3574062	total: 348ms	remaining: 2.29s
132:	learn: 0.3573702	total: 351ms	remaining: 2.29s
133:	learn: 0.3573226	total: 355ms	remaining: 2.29s
134:	learn: 0.3572825	total: 358ms	remaining: 2.29s
135:	learn: 0.3572408	total: 361ms	remaining: 2.3s
136:	learn: 0.3572105	total: 363ms	remaining: 2.29s
137:	learn: 0.3571805	total: 366ms	remaining: 2.29s
138:	learn: 0.3569494	total: 368ms	remaining: 2.28s
139:	learn: 0.3569294	total: 371ms	remaining: 2.28s
140:	learn: 0.3568264	total: 374ms	remaining: 2.28s
141:	learn: 0.3567168	total: 376ms	remaining: 2.27s
142:	learn: 0.3566655	total: 379ms	remaining: 2.27s
143:	learn: 0.3566329	total: 382ms	remaining: 2.27s
144:	learn: 0.3564493	total: 384ms	remaining: 2.27s
145:	learn: 0.3562639	total: 388ms	remaining: 2.27s
146:	learn: 0.3562103	total: 392ms	remaining: 2.27s
147:	learn: 0.3561265	total: 394ms	remaining: 2.27s
148:	learn: 0.3560967	total: 396ms	remaining: 2.26s
149:	learn: 0.3560287	total: 400ms	remaining: 2.27s
150:	learn: 0.3560169	total: 404ms	remaining: 2.27s
151:	learn: 0.3559947	total: 406ms	remaining: 2.26s
152:	learn: 0.3558948	total: 409ms	remaining: 2.26s
153:	learn: 0.3558838	total: 412ms	remaining: 2.26s
154:	learn: 0.3558070	total: 415ms	remaining: 2.26s
155:	learn: 0.3558005	total: 419ms	remaining: 2.27s
156:	learn: 0.3557806	total: 422ms	remaining: 2.26s
157:	learn: 0.3557714	total: 425ms	remaining: 2.27s
158:	learn: 0.3557532	total: 428ms	remaining: 2.26s
159:	learn: 0.3557271	total: 432ms	remaining: 2.27s
160:	learn: 0.3557109	total: 436ms	remaining: 2.27s
161:	learn: 0.3557009	total: 439ms	remaining: 2.27s
162:	learn: 0.3556391	total: 442ms	remaining: 2.27s
163:	learn: 0.3555721	total: 445ms	remaining: 2.27s
164:	learn: 0.3554878	total: 448ms	remaining: 2.27s
165:	learn: 0.3554798	total: 450ms	remaining: 2.26s
166:	learn: 0.3554653	total: 453ms	remaining: 2.26s
167:	learn: 0.3553127	total: 455ms	remaining: 2.25s
168:	learn: 0.3553060	total: 458ms	remaining: 2.25s
169:	learn: 0.3552643	total: 459ms	remaining: 2.24s
170:	learn: 0.3552570	total: 462ms	remaining: 2.24s
171:	learn: 0.3552476	total: 465ms	remaining: 2.24s
172:	learn: 0.3552327	total: 468ms	remaining: 2.24s
173:	learn: 0.3552265	total: 473ms	remaining: 2.24s
174:	learn: 0.3552185	total: 475ms	remaining: 2.24s
175:	learn: 0.3551685	total: 478ms	remaining: 2.24s
176:	learn: 0.3551411	total: 481ms	remaining: 2.24s
177:	learn: 0.3551345	total: 484ms	remaining: 2.24s
178:	learn: 0.3551079	total: 487ms	remaining: 2.23s
179:	learn: 0.3549560	total: 490ms	remaining: 2.23s
180:	learn: 0.3549418	total: 493ms	remaining: 2.23s
181:	learn: 0.3549160	total: 495ms	remaining: 2.23s
182:	learn: 0.3549090	total: 498ms	remaining: 2.22s
183:	learn: 0.3548633	total: 509ms	remaining: 2.25s
184:	learn: 0.3547980	total: 510ms	remaining: 2.25s
185:	learn: 0.3547398	total: 514ms	remaining: 2.25s
186:	learn: 0.3547295	total: 517ms	remaining: 2.25s
187:	learn: 0.3547077	total: 519ms	remaining: 2.24s
188:	learn: 0.3546426	total: 522ms	remaining: 2.24s
189:	learn: 0.3546015	total: 524ms	remaining: 2.23s
190:	learn: 0.3544406	total: 526ms	remaining: 2.23s
191:	learn: 0.3543859	total: 528ms	remaining: 2.22s
192:	learn: 0.3543813	total: 531ms	remaining: 2.22s
193:	learn: 0.3543767	total: 534ms	remaining: 2.22s
194:	learn: 0.3543700	total: 538ms	remaining: 2.22s
195:	learn: 0.3543204	total: 540ms	remaining: 2.22s
196:	learn: 0.3542958	total: 543ms	remaining: 2.21s
197:	learn: 0.3542849	total: 546ms	remaining: 2.21s
198:	learn: 0.3542765	total: 549ms	remaining: 2.21s
199:	learn: 0.3541554	total: 552ms	remaining: 2.21s
200:	learn: 0.3540647	total: 558ms	remaining: 2.22s
201:	learn: 0.3540614	total: 572ms	remaining: 2.26s
202:	learn: 0.3540388	total: 578ms	remaining: 2.27s
203:	learn: 0.3540069	total: 593ms	remaining: 2.31s
204:	learn: 0.3540013	total: 597ms	remaining: 2.31s
205:	learn: 0.3539020	total: 600ms	remaining: 2.31s
206:	learn: 0.3538528	total: 605ms	remaining: 2.32s
207:	learn: 0.3538494	total: 609ms	remaining: 2.32s
208:	learn: 0.3538456	total: 611ms	remaining: 2.31s
209:	learn: 0.3537593	total: 615ms	remaining: 2.31s
210:	learn: 0.3537024	total: 618ms	remaining: 2.31s
211:	learn: 0.3536809	total: 621ms	remaining: 2.31s
212:	learn: 0.3536480	total: 624ms	remaining: 2.31s
213:	learn: 0.3536481	total: 626ms	remaining: 2.3s
214:	learn: 0.3535659	total: 629ms	remaining: 2.3s
215:	learn: 0.3534807	total: 633ms	remaining: 2.29s
216:	learn: 0.3534490	total: 636ms	remaining: 2.29s
217:	learn: 0.3534011	total: 638ms	remaining: 2.29s
218:	learn: 0.3533953	total: 641ms	remaining: 2.28s
219:	learn: 0.3533626	total: 642ms	remaining: 2.28s
220:	learn: 0.3532812	total: 645ms	remaining: 2.27s
221:	learn: 0.3532745	total: 648ms	remaining: 2.27s
222:	learn: 0.3531963	total: 651ms	remaining: 2.27s
223:	learn: 0.3531768	total: 653ms	remaining: 2.26s
224:	learn: 0.3531726	total: 656ms	remaining: 2.26s
225:	learn: 0.3531158	total: 658ms	remaining: 2.25s
226:	learn: 0.3531107	total: 662ms	remaining: 2.25s
227:	learn: 0.3530790	total: 665ms	remaining: 2.25s
228:	learn: 0.3530633	total: 668ms	remaining: 2.25s
229:	learn: 0.3530584	total: 670ms	remaining: 2.24s
230:	learn: 0.3530246	total: 672ms	remaining: 2.24s
231:	learn: 0.3530192	total: 675ms	remaining: 2.23s
232:	learn: 0.3530192	total: 677ms	remaining: 2.23s
233:	learn: 0.3530075	total: 679ms	remaining: 2.22s
234:	learn: 0.3529925	total: 682ms	remaining: 2.22s
235:	learn: 0.3529486	total: 685ms	remaining: 2.22s
236:	learn: 0.3529305	total: 687ms	remaining: 2.21s
237:	learn: 0.3529179	total: 689ms	remaining: 2.21s
238:	learn: 0.3529019	total: 692ms	remaining: 2.2s
239:	learn: 0.3528682	total: 694ms	remaining: 2.2s
240:	learn: 0.3528636	total: 696ms	remaining: 2.19s
241:	learn: 0.3528094	total: 699ms	remaining: 2.19s
242:	learn: 0.3527628	total: 702ms	remaining: 2.19s
243:	learn: 0.3527586	total: 704ms	remaining: 2.18s
244:	learn: 0.3527544	total: 707ms	remaining: 2.18s
245:	learn: 0.3527499	total: 710ms	remaining: 2.17s
246:	learn: 0.3527456	total: 712ms	remaining: 2.17s
247:	learn: 0.3527415	total: 715ms	remaining: 2.17s
248:	learn: 0.3527044	total: 718ms	remaining: 2.16s
249:	learn: 0.3526944	total: 720ms	remaining: 2.16s
250:	learn: 0.3526889	total: 723ms	remaining: 2.16s
251:	learn: 0.3526612	total: 725ms	remaining: 2.15s
252:	learn: 0.3526580	total: 728ms	remaining: 2.15s
253:	learn: 0.3526558	total: 730ms	remaining: 2.14s
254:	learn: 0.3526367	total: 732ms	remaining: 2.14s
255:	learn: 0.3526319	total: 734ms	remaining: 2.13s
256:	learn: 0.3526270	total: 736ms	remaining: 2.13s
257:	learn: 0.3526182	total: 739ms	remaining: 2.13s
258:	learn: 0.3526001	total: 741ms	remaining: 2.12s
259:	learn: 0.3525773	total: 743ms	remaining: 2.12s
260:	learn: 0.3525588	total: 746ms	remaining: 2.11s
261:	learn: 0.3525519	total: 749ms	remaining: 2.11s
262:	learn: 0.3525435	total: 752ms	remaining: 2.11s
263:	learn: 0.3525389	total: 755ms	remaining: 2.1s
264:	learn: 0.3525214	total: 757ms	remaining: 2.1s
265:	learn: 0.3524912	total: 760ms	remaining: 2.1s
266:	learn: 0.3524864	total: 762ms	remaining: 2.09s
267:	learn: 0.3524183	total: 765ms	remaining: 2.09s
268:	learn: 0.3524093	total: 767ms	remaining: 2.08s
269:	learn: 0.3523893	total: 771ms	remaining: 2.08s
270:	learn: 0.3523833	total: 774ms	remaining: 2.08s
271:	learn: 0.3523749	total: 777ms	remaining: 2.08s
272:	learn: 0.3523736	total: 780ms	remaining: 2.08s
273:	learn: 0.3523670	total: 783ms	remaining: 2.07s
274:	learn: 0.3523577	total: 785ms	remaining: 2.07s
275:	learn: 0.3522925	total: 787ms	remaining: 2.06s
276:	learn: 0.3522457	total: 791ms	remaining: 2.06s
277:	learn: 0.3522454	total: 793ms	remaining: 2.06s
278:	learn: 0.3522421	total: 796ms	remaining: 2.06s
279:	learn: 0.3522347	total: 799ms	remaining: 2.05s
280:	learn: 0.3522320	total: 801ms	remaining: 2.05s
281:	learn: 0.3522234	total: 804ms	remaining: 2.04s
282:	learn: 0.3522145	total: 806ms	remaining: 2.04s
283:	learn: 0.3521941	total: 809ms	remaining: 2.04s
284:	learn: 0.3521876	total: 811ms	remaining: 2.04s
285:	learn: 0.3521865	total: 814ms	remaining: 2.03s
286:	learn: 0.3521832	total: 817ms	remaining: 2.03s
287:	learn: 0.3521744	total: 819ms	remaining: 2.02s
288:	learn: 0.3521729	total: 822ms	remaining: 2.02s
289:	learn: 0.3521571	total: 825ms	remaining: 2.02s
290:	learn: 0.3521347	total: 827ms	remaining: 2.02s
291:	learn: 0.3521288	total: 830ms	remaining: 2.01s
292:	learn: 0.3521244	total: 832ms	remaining: 2.01s
293:	learn: 0.3521209	total: 835ms	remaining: 2s
294:	learn: 0.3521140	total: 837ms	remaining: 2s
295:	learn: 0.3521103	total: 840ms	remaining: 2s
296:	learn: 0.3521034	total: 842ms	remaining: 1.99s
297:	learn: 0.3520623	total: 846ms	remaining: 1.99s
298:	learn: 0.3520386	total: 848ms	remaining: 1.99s
299:	learn: 0.3520385	total: 851ms	remaining: 1.98s
300:	learn: 0.3520390	total: 853ms	remaining: 1.98s
301:	learn: 0.3520207	total: 855ms	remaining: 1.98s
302:	learn: 0.3520046	total: 857ms	remaining: 1.97s
303:	learn: 0.3519893	total: 859ms	remaining: 1.97s
304:	learn: 0.3519829	total: 862ms	remaining: 1.96s
305:	learn: 0.3519644	total: 864ms	remaining: 1.96s
306:	learn: 0.3519611	total: 867ms	remaining: 1.96s
307:	learn: 0.3519546	total: 869ms	remaining: 1.95s
308:	learn: 0.3519364	total: 872ms	remaining: 1.95s
309:	learn: 0.3519316	total: 874ms	remaining: 1.95s
310:	learn: 0.3519297	total: 877ms	remaining: 1.94s
311:	learn: 0.3518999	total: 880ms	remaining: 1.94s
312:	learn: 0.3518839	total: 882ms	remaining: 1.94s
313:	learn: 0.3518839	total: 885ms	remaining: 1.93s
314:	learn: 0.3518689	total: 888ms	remaining: 1.93s
315:	learn: 0.3518436	total: 890ms	remaining: 1.93s
316:	learn: 0.3518384	total: 892ms	remaining: 1.92s
317:	learn: 0.3518335	total: 895ms	remaining: 1.92s
318:	learn: 0.3518329	total: 897ms	remaining: 1.92s
319:	learn: 0.3518243	total: 900ms	remaining: 1.91s
320:	learn: 0.3518055	total: 902ms	remaining: 1.91s
321:	learn: 0.3517916	total: 904ms	remaining: 1.9s
322:	learn: 0.3517867	total: 907ms	remaining: 1.9s
323:	learn: 0.3517705	total: 909ms	remaining: 1.9s
324:	learn: 0.3517655	total: 912ms	remaining: 1.89s
325:	learn: 0.3517562	total: 916ms	remaining: 1.89s
326:	learn: 0.3517504	total: 919ms	remaining: 1.89s
327:	learn: 0.3517447	total: 922ms	remaining: 1.89s
328:	learn: 0.3517398	total: 925ms	remaining: 1.89s
329:	learn: 0.3517281	total: 928ms	remaining: 1.88s
330:	learn: 0.3517129	total: 932ms	remaining: 1.88s
331:	learn: 0.3517117	total: 935ms	remaining: 1.88s
332:	learn: 0.3517061	total: 938ms	remaining: 1.88s
333:	learn: 0.3517048	total: 941ms	remaining: 1.88s
334:	learn: 0.3517005	total: 944ms	remaining: 1.87s
335:	learn: 0.3516919	total: 947ms	remaining: 1.87s
336:	learn: 0.3516859	total: 950ms	remaining: 1.87s
337:	learn: 0.3516783	total: 953ms	remaining: 1.86s
338:	learn: 0.3516781	total: 955ms	remaining: 1.86s
339:	learn: 0.3516746	total: 963ms	remaining: 1.87s
340:	learn: 0.3516699	total: 968ms	remaining: 1.87s
341:	learn: 0.3516567	total: 971ms	remaining: 1.87s
342:	learn: 0.3516429	total: 975ms	remaining: 1.87s
343:	learn: 0.3516376	total: 983ms	remaining: 1.87s
344:	learn: 0.3516344	total: 987ms	remaining: 1.87s
345:	learn: 0.3516211	total: 992ms	remaining: 1.87s
346:	learn: 0.3515770	total: 995ms	remaining: 1.87s
347:	learn: 0.3515338	total: 998ms	remaining: 1.87s
348:	learn: 0.3515304	total: 1s	remaining: 1.87s
349:	learn: 0.3515277	total: 1s	remaining: 1.86s
350:	learn: 0.3515150	total: 1.01s	remaining: 1.86s
351:	learn: 0.3515079	total: 1.01s	remaining: 1.86s
352:	learn: 0.3515029	total: 1.01s	remaining: 1.85s
353:	learn: 0.3514901	total: 1.01s	remaining: 1.85s
354:	learn: 0.3514880	total: 1.02s	remaining: 1.85s
355:	learn: 0.3514840	total: 1.02s	remaining: 1.84s
356:	learn: 0.3514421	total: 1.02s	remaining: 1.84s
357:	learn: 0.3514408	total: 1.02s	remaining: 1.84s
358:	learn: 0.3514378	total: 1.03s	remaining: 1.83s
359:	learn: 0.3514346	total: 1.03s	remaining: 1.83s
360:	learn: 0.3514300	total: 1.03s	remaining: 1.83s
361:	learn: 0.3514300	total: 1.03s	remaining: 1.82s
362:	learn: 0.3514306	total: 1.04s	remaining: 1.82s
363:	learn: 0.3514270	total: 1.04s	remaining: 1.82s
364:	learn: 0.3514205	total: 1.04s	remaining: 1.81s
365:	learn: 0.3513782	total: 1.04s	remaining: 1.81s
366:	learn: 0.3513700	total: 1.05s	remaining: 1.81s
367:	learn: 0.3513430	total: 1.05s	remaining: 1.8s
368:	learn: 0.3513209	total: 1.05s	remaining: 1.8s
369:	learn: 0.3513113	total: 1.06s	remaining: 1.8s
370:	learn: 0.3512852	total: 1.06s	remaining: 1.8s
371:	learn: 0.3512723	total: 1.06s	remaining: 1.79s
372:	learn: 0.3512486	total: 1.06s	remaining: 1.79s
373:	learn: 0.3512461	total: 1.07s	remaining: 1.79s
374:	learn: 0.3512433	total: 1.07s	remaining: 1.79s
375:	learn: 0.3512376	total: 1.07s	remaining: 1.78s
376:	learn: 0.3512276	total: 1.08s	remaining: 1.78s
377:	learn: 0.3512244	total: 1.08s	remaining: 1.78s
378:	learn: 0.3512037	total: 1.08s	remaining: 1.78s
379:	learn: 0.3511859	total: 1.09s	remaining: 1.77s
380:	learn: 0.3511826	total: 1.09s	remaining: 1.77s
381:	learn: 0.3511801	total: 1.09s	remaining: 1.77s
382:	learn: 0.3511750	total: 1.09s	remaining: 1.76s
383:	learn: 0.3511751	total: 1.1s	remaining: 1.76s
384:	learn: 0.3511721	total: 1.1s	remaining: 1.76s
385:	learn: 0.3511671	total: 1.1s	remaining: 1.75s
386:	learn: 0.3511621	total: 1.1s	remaining: 1.75s

In [144]:
# Evaluate models
for info in models:
    accuracy,precision,recall,f1=evaluate_model_on_test_data(info["model"])
    info['accuracy']=accuracy
    info["precision"] = precision
    info["recall"] = recall
    info["f1"] = f1
    
# report
df_evaluation_report_test = pd.DataFrame(models, columns=["name", "accuracy", "precision", "recall", "f1"])
df_evaluation_report_test

                  name accuracy precision recall    f1
0  Logistic Regression     0.79      0.78   0.79  0.78
1                  KNN     0.80      0.79   0.79  0.79
2                  SVM     0.82      0.81   0.80  0.80
3        Decision Tree     0.78      0.77   0.76  0.76
4        Random Forest     0.79      0.78   0.78  0.78
5             AdaBoost     0.78      0.77   0.77  0.77
6             CatBoost     0.77      0.76   0.75  0.76

# Que 3

In [ ]:
Que.3
The diabetes.csv dataset contains medical diagnostic measurements of patients. The goal is to analyze these health parameters and predict whether a patient is diabetic or not.
Each record in the dataset represents a patient with the following attributes:
Pregnancies
Glucose
BloodPressure
SkinThickness
Insulin
BMI
DiabetesPedigreeFunction
Age
Outcome (0 = Non-Diabetic, 1 = Diabetic)
Prepare model by using Logistic Regression, KNN, SVM, Decision Tree, Random Forest, AdaBoost, CatBoost & Calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.
Also Prepare summary of all models & Select best of them.

In [145]:
df=pd.read_csv('diabetes.csv')
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [146]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [147]:
df.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [148]:
df.corr()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
Pregnancies,1.000000,0.129459,0.141282,-0.081672,-0.073535,0.017683,-0.033523,0.544341,0.221898
Glucose,0.129459,1.000000,0.152590,0.057328,0.331357,0.221071,0.137337,0.263514,0.466581
BloodPressure,0.141282,0.152590,1.000000,0.207371,0.088933,0.281805,0.041265,0.239528,0.065068
SkinThickness,-0.081672,0.057328,0.207371,1.000000,0.436783,0.392573,0.183928,-0.113970,0.074752
Insulin,-0.073535,0.331357,0.088933,0.436783,1.000000,0.197859,0.185071,-0.042163,0.130548
BMI,0.017683,0.221071,0.281805,0.392573,0.197859,1.000000,0.140647,0.036242,0.292695
DiabetesPedigreeFunction,-0.033523,0.137337,0.041265,0.183928,0.185071,0.140647,1.000000,0.033561,0.173844
Age,0.544341,0.263514,0.239528,-0.113970,-0.042163,0.036242,0.033561,1.000000,0.238356
Outcome,0.221898,0.466581,0.065068,0.074752,0.130548,0.292695,0.173844,0.238356,1.000000

In [149]:
df['Outcome'].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [150]:
x = df.drop('Outcome', axis=1)
y = df['Outcome']

In [151]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, train_size=0.8, random_state=123456
)

In [152]:
## 1. Logistic Regression
from sklearn.linear_model import LogisticRegressionCV
def create_model_logistic_regression():
    model = LogisticRegressionCV()
    model.fit(x_train, y_train)
    return model

In [153]:
## 2. KNN
from sklearn.neighbors import KNeighborsClassifier
def create_knn_model():
    model = KNeighborsClassifier(n_neighbors=5)
    model.fit(x_train, y_train)
    return model

In [154]:
## 3. SVM
from sklearn.svm import SVC
def create_svm_model():
    model = SVC()
    model.fit(x_train, y_train)
    return model

In [155]:
## 4. Decision Tree
from sklearn.tree import DecisionTreeClassifier
def create_decision_tree_model():
    model = DecisionTreeClassifier(max_depth=10)
    model.fit(x_train, y_train)
    return model

In [156]:
## 5. Random Forest
from sklearn.ensemble import RandomForestClassifier
def create_random_forest_model():
    model = RandomForestClassifier(n_estimators=100, max_depth=10)
    model.fit(x_train, y_train)
    return model

In [157]:
## 6. AdaBoost
from sklearn.ensemble import AdaBoostClassifier
def create_adaboost_model():
    model = AdaBoostClassifier(n_estimators=35, learning_rate=0.2)
    model.fit(x_train, y_train)
    return model

In [158]:
## 7. CatBoost
from catboost import CatBoostClassifier
def create_catboost_model():
    model = CatBoostClassifier(learning_rate=0.2)
    model.fit(x_train, y_train)
    return model

In [159]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
def evaluate_model_on_test_data(model):
    y_pred = model.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average="macro")
    recall = recall_score(y_test, y_pred, average="macro")
    f1 = f1_score(y_test, y_pred, average="macro")
    return f"{accuracy:.2f}", f"{precision:.2f}", f"{recall:.2f}", f"{f1:.2f}"

In [160]:
models = []
models.append({"name": "Logistic Regression", "model": create_model_logistic_regression()})
models.append({"name": "KNN", "model": create_knn_model()})
models.append({"name": "SVM", "model": create_svm_model()})
models.append({"name": "Decision Tree", "model": create_decision_tree_model()})
models.append({"name": "Random Forest", "model": create_random_forest_model()})
models.append({"name": "AdaBoost", "model": create_adaboost_model()})
models.append({"name": "CatBoost", "model": create_catboost_model()})

0:	learn: 0.6036166	total: 5.02ms	remaining: 5.01s
1:	learn: 0.5536611	total: 9.67ms	remaining: 4.82s
2:	learn: 0.5119222	total: 13.5ms	remaining: 4.47s
3:	learn: 0.4767969	total: 17.4ms	remaining: 4.34s
4:	learn: 0.4544309	total: 21.3ms	remaining: 4.23s
5:	learn: 0.4350368	total: 24.7ms	remaining: 4.09s
6:	learn: 0.4174814	total: 28.6ms	remaining: 4.06s
7:	learn: 0.3947012	total: 32.5ms	remaining: 4.03s
8:	learn: 0.3881874	total: 36.6ms	remaining: 4.03s
9:	learn: 0.3784292	total: 40.6ms	remaining: 4.02s
10:	learn: 0.3688366	total: 44.5ms	remaining: 4s
11:	learn: 0.3634237	total: 48.7ms	remaining: 4.01s
12:	learn: 0.3565164	total: 53.1ms	remaining: 4.03s
13:	learn: 0.3507827	total: 58.2ms	remaining: 4.1s
14:	learn: 0.3399296	total: 62.5ms	remaining: 4.11s
15:	learn: 0.3363428	total: 66.8ms	remaining: 4.11s
16:	learn: 0.3297249	total: 71.5ms	remaining: 4.14s
17:	learn: 0.3216258	total: 74.8ms	remaining: 4.08s
18:	learn: 0.3145814	total: 79.7ms	remaining: 4.11s
19:	learn: 0.3131365	total: 82.7ms	remaining: 4.05s
20:	learn: 0.3099494	total: 87.1ms	remaining: 4.06s
21:	learn: 0.3057838	total: 90.3ms	remaining: 4.01s
22:	learn: 0.3012910	total: 94.6ms	remaining: 4.02s
23:	learn: 0.2955639	total: 98ms	remaining: 3.99s
24:	learn: 0.2880373	total: 102ms	remaining: 3.98s
25:	learn: 0.2823840	total: 106ms	remaining: 3.99s
26:	learn: 0.2745587	total: 110ms	remaining: 3.96s
27:	learn: 0.2711254	total: 114ms	remaining: 3.96s
28:	learn: 0.2655615	total: 117ms	remaining: 3.93s
29:	learn: 0.2602197	total: 122ms	remaining: 3.93s
30:	learn: 0.2568503	total: 125ms	remaining: 3.9s
31:	learn: 0.2528811	total: 129ms	remaining: 3.89s
32:	learn: 0.2481991	total: 132ms	remaining: 3.87s
33:	learn: 0.2417323	total: 136ms	remaining: 3.86s
34:	learn: 0.2388648	total: 139ms	remaining: 3.84s
35:	learn: 0.2344996	total: 143ms	remaining: 3.82s
36:	learn: 0.2287553	total: 147ms	remaining: 3.82s
37:	learn: 0.2224436	total: 150ms	remaining: 3.8s
38:	learn: 0.2210000	total: 154ms	remaining: 3.78s
39:	learn: 0.2133150	total: 157ms	remaining: 3.77s
40:	learn: 0.2108405	total: 160ms	remaining: 3.75s
41:	learn: 0.2040067	total: 164ms	remaining: 3.74s
42:	learn: 0.2014986	total: 167ms	remaining: 3.73s
43:	learn: 0.1945655	total: 171ms	remaining: 3.71s
44:	learn: 0.1897250	total: 181ms	remaining: 3.83s
45:	learn: 0.1867734	total: 191ms	remaining: 3.96s
46:	learn: 0.1839671	total: 205ms	remaining: 4.15s
47:	learn: 0.1810424	total: 217ms	remaining: 4.31s
48:	learn: 0.1801284	total: 230ms	remaining: 4.46s
49:	learn: 0.1773275	total: 239ms	remaining: 4.53s
50:	learn: 0.1731870	total: 248ms	remaining: 4.62s
51:	learn: 0.1725278	total: 258ms	remaining: 4.7s
52:	learn: 0.1702129	total: 263ms	remaining: 4.69s
53:	learn: 0.1678628	total: 268ms	remaining: 4.69s
54:	learn: 0.1649530	total: 273ms	remaining: 4.69s
55:	learn: 0.1597775	total: 278ms	remaining: 4.68s
56:	learn: 0.1579852	total: 283ms	remaining: 4.68s
57:	learn: 0.1553990	total: 289ms	remaining: 4.69s
58:	learn: 0.1527341	total: 293ms	remaining: 4.67s
59:	learn: 0.1519057	total: 300ms	remaining: 4.69s
60:	learn: 0.1483466	total: 305ms	remaining: 4.7s
61:	learn: 0.1445706	total: 310ms	remaining: 4.7s
62:	learn: 0.1418178	total: 315ms	remaining: 4.68s
63:	learn: 0.1404644	total: 319ms	remaining: 4.66s
64:	learn: 0.1379324	total: 322ms	remaining: 4.63s
65:	learn: 0.1372738	total: 326ms	remaining: 4.61s
66:	learn: 0.1355213	total: 330ms	remaining: 4.59s
67:	learn: 0.1324684	total: 334ms	remaining: 4.58s
68:	learn: 0.1322920	total: 337ms	remaining: 4.55s
69:	learn: 0.1318921	total: 341ms	remaining: 4.53s
70:	learn: 0.1309060	total: 345ms	remaining: 4.51s
71:	learn: 0.1283540	total: 349ms	remaining: 4.5s
72:	learn: 0.1260389	total: 354ms	remaining: 4.49s
73:	learn: 0.1223118	total: 359ms	remaining: 4.49s
74:	learn: 0.1183142	total: 363ms	remaining: 4.47s
75:	learn: 0.1161989	total: 367ms	remaining: 4.46s
76:	learn: 0.1144937	total: 370ms	remaining: 4.44s
77:	learn: 0.1128901	total: 374ms	remaining: 4.42s
78:	learn: 0.1109934	total: 377ms	remaining: 4.4s
79:	learn: 0.1105746	total: 381ms	remaining: 4.38s
80:	learn: 0.1087324	total: 385ms	remaining: 4.36s
81:	learn: 0.1083421	total: 388ms	remaining: 4.34s
82:	learn: 0.1062953	total: 392ms	remaining: 4.33s
83:	learn: 0.1052462	total: 395ms	remaining: 4.31s
84:	learn: 0.1034323	total: 398ms	remaining: 4.29s
85:	learn: 0.1029662	total: 403ms	remaining: 4.28s
86:	learn: 0.1022800	total: 408ms	remaining: 4.28s
87:	learn: 0.1003122	total: 412ms	remaining: 4.27s
88:	learn: 0.0985665	total: 415ms	remaining: 4.25s
89:	learn: 0.0971301	total: 419ms	remaining: 4.23s
90:	learn: 0.0950470	total: 424ms	remaining: 4.23s
91:	learn: 0.0931336	total: 427ms	remaining: 4.22s
92:	learn: 0.0917979	total: 431ms	remaining: 4.2s
93:	learn: 0.0895324	total: 434ms	remaining: 4.19s
94:	learn: 0.0877078	total: 439ms	remaining: 4.18s
95:	learn: 0.0859980	total: 443ms	remaining: 4.17s
96:	learn: 0.0842811	total: 447ms	remaining: 4.16s
97:	learn: 0.0828712	total: 450ms	remaining: 4.15s
98:	learn: 0.0815929	total: 454ms	remaining: 4.13s
99:	learn: 0.0795567	total: 458ms	remaining: 4.12s
100:	learn: 0.0787899	total: 461ms	remaining: 4.11s
101:	learn: 0.0785475	total: 465ms	remaining: 4.09s
102:	learn: 0.0780606	total: 468ms	remaining: 4.08s
103:	learn: 0.0769096	total: 472ms	remaining: 4.07s
104:	learn: 0.0757019	total: 476ms	remaining: 4.05s
105:	learn: 0.0746870	total: 479ms	remaining: 4.04s
106:	learn: 0.0737776	total: 482ms	remaining: 4.03s
107:	learn: 0.0719765	total: 486ms	remaining: 4.02s
108:	learn: 0.0701720	total: 495ms	remaining: 4.05s
109:	learn: 0.0695893	total: 504ms	remaining: 4.08s
110:	learn: 0.0677925	total: 516ms	remaining: 4.13s
111:	learn: 0.0676859	total: 526ms	remaining: 4.17s
112:	learn: 0.0667322	total: 538ms	remaining: 4.22s
113:	learn: 0.0657762	total: 548ms	remaining: 4.26s
114:	learn: 0.0641021	total: 558ms	remaining: 4.3s
115:	learn: 0.0635645	total: 568ms	remaining: 4.33s
116:	learn: 0.0622808	total: 575ms	remaining: 4.34s
117:	learn: 0.0620574	total: 580ms	remaining: 4.33s
118:	learn: 0.0612498	total: 586ms	remaining: 4.34s
119:	learn: 0.0609241	total: 591ms	remaining: 4.33s
120:	learn: 0.0595235	total: 597ms	remaining: 4.34s
121:	learn: 0.0583766	total: 606ms	remaining: 4.36s
122:	learn: 0.0572466	total: 612ms	remaining: 4.36s
123:	learn: 0.0564651	total: 623ms	remaining: 4.4s
124:	learn: 0.0561814	total: 629ms	remaining: 4.4s
125:	learn: 0.0552222	total: 633ms	remaining: 4.39s
126:	learn: 0.0543117	total: 637ms	remaining: 4.38s
127:	learn: 0.0531375	total: 641ms	remaining: 4.37s
128:	learn: 0.0523016	total: 645ms	remaining: 4.36s
129:	learn: 0.0513633	total: 649ms	remaining: 4.34s
130:	learn: 0.0503921	total: 653ms	remaining: 4.33s
131:	learn: 0.0501824	total: 659ms	remaining: 4.33s
132:	learn: 0.0490514	total: 662ms	remaining: 4.32s
133:	learn: 0.0481710	total: 666ms	remaining: 4.3s
134:	learn: 0.0476423	total: 669ms	remaining: 4.29s
135:	learn: 0.0472239	total: 674ms	remaining: 4.28s
136:	learn: 0.0468565	total: 679ms	remaining: 4.27s
137:	learn: 0.0468000	total: 682ms	remaining: 4.26s
138:	learn: 0.0464046	total: 686ms	remaining: 4.25s
139:	learn: 0.0458189	total: 689ms	remaining: 4.23s
140:	learn: 0.0449228	total: 692ms	remaining: 4.22s
141:	learn: 0.0443857	total: 696ms	remaining: 4.2s
142:	learn: 0.0443285	total: 699ms	remaining: 4.19s
143:	learn: 0.0437979	total: 703ms	remaining: 4.18s
144:	learn: 0.0437295	total: 707ms	remaining: 4.17s
145:	learn: 0.0436956	total: 711ms	remaining: 4.16s
146:	learn: 0.0434972	total: 715ms	remaining: 4.15s
147:	learn: 0.0430796	total: 719ms	remaining: 4.14s
148:	learn: 0.0426427	total: 723ms	remaining: 4.13s
149:	learn: 0.0420309	total: 726ms	remaining: 4.11s
150:	learn: 0.0415672	total: 729ms	remaining: 4.1s
151:	learn: 0.0409922	total: 733ms	remaining: 4.09s
152:	learn: 0.0402604	total: 737ms	remaining: 4.08s
153:	learn: 0.0402403	total: 741ms	remaining: 4.07s
154:	learn: 0.0395568	total: 745ms	remaining: 4.06s
155:	learn: 0.0392492	total: 749ms	remaining: 4.05s
156:	learn: 0.0385070	total: 753ms	remaining: 4.04s
157:	learn: 0.0381970	total: 756ms	remaining: 4.03s
158:	learn: 0.0380316	total: 761ms	remaining: 4.02s
159:	learn: 0.0378032	total: 764ms	remaining: 4.01s
160:	learn: 0.0370533	total: 769ms	remaining: 4s
161:	learn: 0.0366822	total: 773ms	remaining: 4s
162:	learn: 0.0360895	total: 793ms	remaining: 4.07s
163:	learn: 0.0354810	total: 805ms	remaining: 4.1s
164:	learn: 0.0351504	total: 825ms	remaining: 4.17s
165:	learn: 0.0346527	total: 844ms	remaining: 4.24s
166:	learn: 0.0343159	total: 865ms	remaining: 4.31s
167:	learn: 0.0342016	total: 871ms	remaining: 4.31s
168:	learn: 0.0339768	total: 877ms	remaining: 4.31s
169:	learn: 0.0339158	total: 883ms	remaining: 4.31s
170:	learn: 0.0338076	total: 892ms	remaining: 4.33s
171:	learn: 0.0336499	total: 897ms	remaining: 4.32s
172:	learn: 0.0332572	total: 901ms	remaining: 4.31s
173:	learn: 0.0327358	total: 905ms	remaining: 4.3s
174:	learn: 0.0326309	total: 909ms	remaining: 4.29s
175:	learn: 0.0326077	total: 912ms	remaining: 4.27s
176:	learn: 0.0324380	total: 917ms	remaining: 4.26s
177:	learn: 0.0321531	total: 922ms	remaining: 4.26s
178:	learn: 0.0320845	total: 925ms	remaining: 4.24s
179:	learn: 0.0317665	total: 930ms	remaining: 4.24s
180:	learn: 0.0313949	total: 934ms	remaining: 4.22s
181:	learn: 0.0312402	total: 938ms	remaining: 4.22s
182:	learn: 0.0310062	total: 943ms	remaining: 4.21s
183:	learn: 0.0307114	total: 949ms	remaining: 4.21s
184:	learn: 0.0304650	total: 953ms	remaining: 4.2s
185:	learn: 0.0301195	total: 957ms	remaining: 4.19s
186:	learn: 0.0298392	total: 962ms	remaining: 4.18s
187:	learn: 0.0293462	total: 966ms	remaining: 4.17s
188:	learn: 0.0291365	total: 971ms	remaining: 4.17s
189:	learn: 0.0286372	total: 975ms	remaining: 4.15s
190:	learn: 0.0284505	total: 978ms	remaining: 4.14s
191:	learn: 0.0283307	total: 981ms	remaining: 4.13s
192:	learn: 0.0282350	total: 985ms	remaining: 4.12s
193:	learn: 0.0281021	total: 990ms	remaining: 4.11s
194:	learn: 0.0277434	total: 995ms	remaining: 4.11s
195:	learn: 0.0274405	total: 999ms	remaining: 4.1s
196:	learn: 0.0272897	total: 1s	remaining: 4.09s
197:	learn: 0.0269634	total: 1.01s	remaining: 4.08s
198:	learn: 0.0268467	total: 1.01s	remaining: 4.07s
199:	learn: 0.0268057	total: 1.02s	remaining: 4.07s
200:	learn: 0.0266659	total: 1.02s	remaining: 4.06s
201:	learn: 0.0266083	total: 1.02s	remaining: 4.05s
202:	learn: 0.0265080	total: 1.03s	remaining: 4.04s
203:	learn: 0.0261561	total: 1.03s	remaining: 4.03s
204:	learn: 0.0259779	total: 1.04s	remaining: 4.05s
205:	learn: 0.0256532	total: 1.05s	remaining: 4.07s
206:	learn: 0.0254475	total: 1.07s	remaining: 4.09s
207:	learn: 0.0253363	total: 1.08s	remaining: 4.11s
208:	learn: 0.0250597	total: 1.1s	remaining: 4.16s
209:	learn: 0.0249128	total: 1.11s	remaining: 4.19s
210:	learn: 0.0247041	total: 1.12s	remaining: 4.19s
211:	learn: 0.0244717	total: 1.13s	remaining: 4.18s
212:	learn: 0.0242867	total: 1.13s	remaining: 4.18s
213:	learn: 0.0240517	total: 1.13s	remaining: 4.17s
214:	learn: 0.0236660	total: 1.14s	remaining: 4.16s
215:	learn: 0.0234477	total: 1.14s	remaining: 4.15s
216:	learn: 0.0233140	total: 1.15s	remaining: 4.14s
217:	learn: 0.0231552	total: 1.15s	remaining: 4.13s
218:	learn: 0.0230719	total: 1.16s	remaining: 4.12s
219:	learn: 0.0230660	total: 1.16s	remaining: 4.11s
220:	learn: 0.0229847	total: 1.16s	remaining: 4.1s
221:	learn: 0.0228239	total: 1.17s	remaining: 4.09s
222:	learn: 0.0225283	total: 1.17s	remaining: 4.08s
223:	learn: 0.0223882	total: 1.18s	remaining: 4.07s
224:	learn: 0.0223353	total: 1.18s	remaining: 4.06s
225:	learn: 0.0221215	total: 1.18s	remaining: 4.06s
226:	learn: 0.0219105	total: 1.19s	remaining: 4.05s
227:	learn: 0.0218039	total: 1.19s	remaining: 4.04s
228:	learn: 0.0216586	total: 1.2s	remaining: 4.03s
229:	learn: 0.0214850	total: 1.2s	remaining: 4.03s
230:	learn: 0.0213750	total: 1.21s	remaining: 4.01s
231:	learn: 0.0211790	total: 1.21s	remaining: 4s
232:	learn: 0.0210513	total: 1.21s	remaining: 3.99s
233:	learn: 0.0209292	total: 1.22s	remaining: 3.98s
234:	learn: 0.0207437	total: 1.22s	remaining: 3.98s
235:	learn: 0.0206393	total: 1.23s	remaining: 3.99s
236:	learn: 0.0206051	total: 1.24s	remaining: 3.99s
237:	learn: 0.0203547	total: 1.24s	remaining: 3.98s
238:	learn: 0.0201218	total: 1.25s	remaining: 3.97s
239:	learn: 0.0198631	total: 1.25s	remaining: 3.96s
240:	learn: 0.0198233	total: 1.25s	remaining: 3.95s
241:	learn: 0.0197051	total: 1.26s	remaining: 3.94s
242:	learn: 0.0194670	total: 1.26s	remaining: 3.93s
243:	learn: 0.0192587	total: 1.27s	remaining: 3.92s
244:	learn: 0.0192440	total: 1.27s	remaining: 3.92s
245:	learn: 0.0192301	total: 1.27s	remaining: 3.91s
246:	learn: 0.0190747	total: 1.28s	remaining: 3.9s
247:	learn: 0.0189553	total: 1.28s	remaining: 3.89s
248:	learn: 0.0188747	total: 1.29s	remaining: 3.88s
249:	learn: 0.0187039	total: 1.29s	remaining: 3.88s
250:	learn: 0.0186114	total: 1.3s	remaining: 3.89s
251:	learn: 0.0183385	total: 1.31s	remaining: 3.9s
252:	learn: 0.0181420	total: 1.32s	remaining: 3.91s
253:	learn: 0.0180054	total: 1.33s	remaining: 3.91s
254:	learn: 0.0179162	total: 1.34s	remaining: 3.92s
255:	learn: 0.0177288	total: 1.35s	remaining: 3.93s
256:	learn: 0.0175006	total: 1.36s	remaining: 3.94s
257:	learn: 0.0173576	total: 1.38s	remaining: 3.96s
258:	learn: 0.0172282	total: 1.38s	remaining: 3.96s
259:	learn: 0.0171386	total: 1.39s	remaining: 3.95s
260:	learn: 0.0170181	total: 1.39s	remaining: 3.95s
261:	learn: 0.0169923	total: 1.4s	remaining: 3.94s
262:	learn: 0.0169010	total: 1.41s	remaining: 3.94s
263:	learn: 0.0168101	total: 1.41s	remaining: 3.93s
264:	learn: 0.0167525	total: 1.42s	remaining: 3.92s
265:	learn: 0.0166248	total: 1.42s	remaining: 3.92s
266:	learn: 0.0165207	total: 1.43s	remaining: 3.92s
267:	learn: 0.0164317	total: 1.43s	remaining: 3.91s
268:	learn: 0.0163796	total: 1.45s	remaining: 3.93s
269:	learn: 0.0163440	total: 1.45s	remaining: 3.92s
270:	learn: 0.0162928	total: 1.45s	remaining: 3.91s
271:	learn: 0.0161800	total: 1.46s	remaining: 3.91s
272:	learn: 0.0161543	total: 1.46s	remaining: 3.9s
273:	learn: 0.0161036	total: 1.47s	remaining: 3.89s
274:	learn: 0.0159211	total: 1.47s	remaining: 3.88s
275:	learn: 0.0158336	total: 1.48s	remaining: 3.88s
276:	learn: 0.0157090	total: 1.48s	remaining: 3.87s
277:	learn: 0.0156813	total: 1.48s	remaining: 3.86s
278:	learn: 0.0155549	total: 1.49s	remaining: 3.85s
279:	learn: 0.0154770	total: 1.49s	remaining: 3.84s
280:	learn: 0.0154167	total: 1.5s	remaining: 3.83s
281:	learn: 0.0153150	total: 1.5s	remaining: 3.82s
282:	learn: 0.0152280	total: 1.51s	remaining: 3.82s
283:	learn: 0.0151647	total: 1.51s	remaining: 3.81s
284:	learn: 0.0150631	total: 1.51s	remaining: 3.8s
285:	learn: 0.0150277	total: 1.52s	remaining: 3.79s
286:	learn: 0.0149803	total: 1.52s	remaining: 3.79s
287:	learn: 0.0149609	total: 1.53s	remaining: 3.78s
288:	learn: 0.0148968	total: 1.53s	remaining: 3.77s
289:	learn: 0.0148752	total: 1.53s	remaining: 3.76s
290:	learn: 0.0147987	total: 1.54s	remaining: 3.75s
291:	learn: 0.0146718	total: 1.54s	remaining: 3.74s
292:	learn: 0.0146719	total: 1.55s	remaining: 3.73s
293:	learn: 0.0145654	total: 1.55s	remaining: 3.73s
294:	learn: 0.0144313	total: 1.55s	remaining: 3.72s
295:	learn: 0.0144198	total: 1.56s	remaining: 3.71s
296:	learn: 0.0143925	total: 1.56s	remaining: 3.7s
297:	learn: 0.0143178	total: 1.57s	remaining: 3.69s
298:	learn: 0.0142708	total: 1.57s	remaining: 3.68s
299:	learn: 0.0142661	total: 1.57s	remaining: 3.68s
300:	learn: 0.0142029	total: 1.58s	remaining: 3.67s
301:	learn: 0.0141411	total: 1.58s	remaining: 3.66s
302:	learn: 0.0140233	total: 1.59s	remaining: 3.65s
303:	learn: 0.0138729	total: 1.59s	remaining: 3.65s
304:	learn: 0.0138468	total: 1.6s	remaining: 3.64s
305:	learn: 0.0138113	total: 1.6s	remaining: 3.63s
306:	learn: 0.0137347	total: 1.6s	remaining: 3.62s
307:	learn: 0.0137314	total: 1.61s	remaining: 3.62s
308:	learn: 0.0137083	total: 1.61s	remaining: 3.61s
309:	learn: 0.0136304	total: 1.62s	remaining: 3.6s
310:	learn: 0.0135975	total: 1.62s	remaining: 3.59s
311:	learn: 0.0134753	total: 1.63s	remaining: 3.58s
312:	learn: 0.0133473	total: 1.63s	remaining: 3.58s
313:	learn: 0.0132566	total: 1.63s	remaining: 3.57s
314:	learn: 0.0131397	total: 1.65s	remaining: 3.58s
315:	learn: 0.0130860	total: 1.67s	remaining: 3.61s
316:	learn: 0.0130320	total: 1.68s	remaining: 3.61s
317:	learn: 0.0129755	total: 1.7s	remaining: 3.63s
318:	learn: 0.0128912	total: 1.71s	remaining: 3.64s
319:	learn: 0.0127777	total: 1.72s	remaining: 3.66s
320:	learn: 0.0127625	total: 1.73s	remaining: 3.67s
321:	learn: 0.0127222	total: 1.74s	remaining: 3.66s
322:	learn: 0.0126372	total: 1.75s	remaining: 3.66s
323:	learn: 0.0125782	total: 1.75s	remaining: 3.65s
324:	learn: 0.0125677	total: 1.75s	remaining: 3.65s
325:	learn: 0.0124402	total: 1.76s	remaining: 3.64s
326:	learn: 0.0124039	total: 1.77s	remaining: 3.63s
327:	learn: 0.0123800	total: 1.77s	remaining: 3.63s
328:	learn: 0.0123801	total: 1.78s	remaining: 3.62s
329:	learn: 0.0123681	total: 1.78s	remaining: 3.61s
330:	learn: 0.0122781	total: 1.78s	remaining: 3.6s
331:	learn: 0.0122385	total: 1.79s	remaining: 3.6s
332:	learn: 0.0122020	total: 1.79s	remaining: 3.59s
333:	learn: 0.0121824	total: 1.79s	remaining: 3.58s
334:	learn: 0.0121166	total: 1.8s	remaining: 3.57s
335:	learn: 0.0120294	total: 1.8s	remaining: 3.56s
336:	learn: 0.0119638	total: 1.81s	remaining: 3.55s
337:	learn: 0.0118793	total: 1.81s	remaining: 3.55s
338:	learn: 0.0117746	total: 1.81s	remaining: 3.54s
339:	learn: 0.0117555	total: 1.82s	remaining: 3.53s
340:	learn: 0.0117076	total: 1.82s	remaining: 3.52s
341:	learn: 0.0116423	total: 1.83s	remaining: 3.52s
342:	learn: 0.0116048	total: 1.83s	remaining: 3.51s
343:	learn: 0.0115393	total: 1.83s	remaining: 3.5s
344:	learn: 0.0114972	total: 1.84s	remaining: 3.49s
345:	learn: 0.0114972	total: 1.84s	remaining: 3.48s
346:	learn: 0.0114686	total: 1.85s	remaining: 3.48s
347:	learn: 0.0114144	total: 1.85s	remaining: 3.47s
348:	learn: 0.0113874	total: 1.86s	remaining: 3.46s
349:	learn: 0.0113422	total: 1.86s	remaining: 3.45s
350:	learn: 0.0112852	total: 1.86s	remaining: 3.45s
351:	learn: 0.0112241	total: 1.87s	remaining: 3.44s
352:	learn: 0.0112044	total: 1.87s	remaining: 3.43s
353:	learn: 0.0111718	total: 1.88s	remaining: 3.42s
354:	learn: 0.0110831	total: 1.88s	remaining: 3.42s
355:	learn: 0.0110790	total: 1.88s	remaining: 3.41s
356:	learn: 0.0110000	total: 1.89s	remaining: 3.4s
357:	learn: 0.0108948	total: 1.89s	remaining: 3.39s
358:	learn: 0.0108559	total: 1.9s	remaining: 3.38s
359:	learn: 0.0108023	total: 1.9s	remaining: 3.38s
360:	learn: 0.0106878	total: 1.9s	remaining: 3.37s
361:	learn: 0.0106457	total: 1.91s	remaining: 3.36s
362:	learn: 0.0105576	total: 1.91s	remaining: 3.35s
363:	learn: 0.0105575	total: 1.91s	remaining: 3.34s
364:	learn: 0.0105471	total: 1.92s	remaining: 3.34s
365:	learn: 0.0105368	total: 1.92s	remaining: 3.33s
366:	learn: 0.0104181	total: 1.92s	remaining: 3.32s
367:	learn: 0.0103738	total: 1.93s	remaining: 3.31s
368:	learn: 0.0102754	total: 1.93s	remaining: 3.3s
369:	learn: 0.0102503	total: 1.93s	remaining: 3.29s
370:	learn: 0.0101926	total: 1.94s	remaining: 3.29s
371:	learn: 0.0101553	total: 1.94s	remaining: 3.28s
372:	learn: 0.0101160	total: 1.95s	remaining: 3.27s
373:	learn: 0.0101161	total: 1.95s	remaining: 3.26s
374:	learn: 0.0100654	total: 1.95s	remaining: 3.25s
375:	learn: 0.0099836	total: 1.96s	remaining: 3.25s
376:	learn: 0.0099836	total: 1.96s	remaining: 3.24s
377:	learn: 0.0099287	total: 1.96s	remaining: 3.23s
378:	learn: 0.0099188	total: 1.97s	remaining: 3.22s
379:	learn: 0.0098931	total: 1.97s	remaining: 3.21s
380:	learn: 0.0098565	total: 1.97s	remaining: 3.21s
381:	learn: 0.0097920	total: 1.98s	remaining: 3.2s
382:	learn: 0.0097033	total: 1.98s	remaining: 3.19s
383:	learn: 0.0096377	total: 1.98s	remaining: 3.18s
384:	learn: 0.0096284	total: 1.99s	remaining: 3.18s
385:	learn: 0.0095503	total: 1.99s	remaining: 3.17s
386:	learn: 0.0094958	total: 2s	remaining: 3.16s

In [161]:
# Evaluate models
for info in models:
    accuracy,precision,recall,f1=evaluate_model_on_test_data(info["model"])
    info['accuracy']=accuracy
    info["precision"] = precision
    info["recall"] = recall
    info["f1"] = f1
    
# report
df_evaluation_report_test = pd.DataFrame(models, columns=["name", "accuracy", "precision", "recall", "f1"])
df_evaluation_report_test

                  name accuracy precision recall    f1
0  Logistic Regression     0.75      0.76   0.73  0.73
1                  KNN     0.68      0.67   0.66  0.66
2                  SVM     0.72      0.75   0.69  0.69
3        Decision Tree     0.71      0.71   0.69  0.70
4        Random Forest     0.75      0.76   0.74  0.74
5             AdaBoost     0.73      0.73   0.71  0.71
6             CatBoost     0.74      0.74   0.73  0.73

## Que 4

In [163]:
df = pd.read_csv('ObesityLevel.csv')
df.head()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
0,21.0,Female,1.62,64.0,no,no,2.0,3.0,no,no,2.0,yes,0.0,1.0,Sometimes,Public_Transportation,Normal_Weight
1,21.0,Female,1.52,56.0,Sometimes,no,3.0,3.0,yes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,23.0,Male,1.80,77.0,Frequently,no,2.0,3.0,no,no,2.0,yes,2.0,1.0,Sometimes,Public_Transportation,Normal_Weight
3,27.0,Male,1.80,87.0,Frequently,no,3.0,3.0,no,no,2.0,no,2.0,0.0,Sometimes,Walking,Overweight_Level_I
4,22.0,Male,1.78,89.8,Sometimes,no,2.0,1.0,no,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [164]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Age                             2111 non-null   float64
 1   Gender                          2111 non-null   object
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   CALC                            2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   SCC                             2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  family_history_with_overweight  2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CAEC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [165]:
df.isna().sum()

Age                               0
Gender                            0
Height                            0
Weight                            0
CALC                              0
FAVC                              0
FCVC                              0
NCP                               0
SCC                               0
SMOKE                             0
CH2O                              0
family_history_with_overweight    0
FAF                               0
TUE                               0
CAEC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

In [172]:
from sklearn.preprocessing import LabelEncoder
df['Gender'] = LabelEncoder().fit_transform(df['Gender'])
df['CALC'] = LabelEncoder().fit_transform(df['CALC'])
df['FAVC'] = LabelEncoder().fit_transform(df['FAVC'])
df['SCC'] = LabelEncoder().fit_transform(df['SCC'])
df['SMOKE'] = LabelEncoder().fit_transform(df['SMOKE'])
df['family_history_with_overweight'] = LabelEncoder().fit_transform(df['family_history_with_overweight'])
df['CAEC'] = LabelEncoder().fit_transform(df['CAEC'])
df['MTRANS'] = LabelEncoder().fit_transform(df['MTRANS'])
df['NObeyesdad'] = LabelEncoder().fit_transform(df['NObeyesdad'])

In [173]:
df.corr()

,Age,Gender,Height,Weight,CALC,FAVC,FCVC,NCP,SCC,SMOKE,CH2O,family_history_with_overweight,FAF,TUE,CAEC,MTRANS,NObeyesdad
Age,1.000000,0.048394,-0.025958,0.202560,-0.044487,0.063902,0.016291,-0.043944,-0.116283,0.091987,-0.045304,0.205725,-0.144938,-0.296931,0.083739,-0.601945,0.236170
Gender,0.048394,1.000000,0.618466,0.161668,0.007616,0.064934,-0.274505,0.067600,-0.102633,0.044698,0.107930,0.102512,0.189607,0.017269,0.091543,-0.137537,0.024908
Height,-0.025958,0.618466,1.000000,0.463136,-0.129732,0.178364,-0.038121,0.243672,-0.133753,0.055499,0.213376,0.247684,0.294709,0.051912,0.048818,-0.073609,0.038986
Weight,0.202560,0.161668,0.463136,1.000000,-0.206677,0.272300,0.216125,0.107469,-0.201906,0.025746,0.200575,0.496820,-0.051436,-0.071561,0.287493,0.004610,0.387643
CALC,-0.044487,0.007616,-0.129732,-0.206677,1.000000,-0.089520,-0.060781,-0.071747,-0.003463,-0.082471,-0.091386,0.036676,0.086799,0.045864,-0.047540,-0.012452,-0.134632
FAVC,0.063902,0.064934,0.178364,0.272300,-0.089520,1.000000,-0.027283,-0.007000,-0.190658,-0.050660,0.009719,0.208036,-0.107995,0.068417,0.150068,-0.069800,0.044582
FCVC,0.016291,-0.274505,-0.038121,0.216125,-0.060781,-0.027283,1.000000,0.042216,0.071852,0.014320,0.068461,0.040372,0.019939,-0.101135,-0.054670,0.064743,0.018522
NCP,-0.043944,0.067600,0.243672,0.107469,-0.071747,-0.007000,0.042216,1.000000,-0.015624,0.007811,0.057088,0.071370,0.129504,0.036326,-0.097801,-0.053858,-0.092616
SCC,-0.116283,-0.102633,-0.133753,-0.201906,-0.003463,-0.190658,0.071852,-0.015624,1.000000,0.047731,0.008036,-0.185422,0.074221,-0.010928,-0.109179,0.043157,-0.050679
SMOKE,0.091987,0.044698,0.055499,0.025746,-0.082471,-0.050660,0.014320,0.007811,0.047731,1.000000,-0.031995,0.017385,0.011216,0.017613,-0.055282,-0.010702,-0.023256
CH2O,-0.045304,0.107930,0.213376,0.200575,-0.091386,0.009719,0.068461,0.057088,0.008036,-0.031995,1.000000,0.147437,0.167236,0.011965,0.144995,0.044028,0.108868
family_history_with_overweight,0.205725,0.102512,0.247684,0.496820,0.036676,0.208036,0.040372,0.071370,-0.185422,0.017385,0.147437,1.000000,-0.056673,0.022943,0.169787,-0.101540,0.313667
FAF,-0.144938,0.189607,0.294709,-0.051436,0.086799,-0.107995,0.019939,0.129504,0.074221,0.011216,0.167236,-0.056673,1.000000,0.058562,-0.030110,0.006394,-0.129564
TUE,-0.296931,0.017269,0.051912,-0.071561,0.045864,0.068417,-0.101135,0.036326,-0.010928,0.017613,0.011965,0.022943,0.058562,1.000000,-0.048567,0.176945,-0.069448
CAEC,0.083739,0.091543,0.048818,0.287493,-0.047540,0.150068,-0.054670,-0.097801,-0.109179,-0.055282,0.144995,0.169787,-0.030110,-0.048567,1.000000,-0.048535,0.327295
MTRANS,-0.601945,-0.137537,-0.073609,0.004610,-0.012452,-0.069800,0.064743,-0.053858,0.043157,-0.010702,0.044028,-0.101540,0.006394,0.176945,-0.048535,1.000000,-0.046202
NObeyesdad,0.236170,0.024908,0.038986,0.387643,-0.134632,0.044582,0.018522,-0.092616,-0.050679,-0.023256,0.108868,0.313667,-0.129564,-0.069448,0.327295,-0.046202,1.000000

In [174]:
df.drop(['CALC','NCP','SCC','SMOKE','FAF','TUE','MTRANS'],axis=1,inplace=True)

In [175]:
x = df.drop('NObeyesdad', axis=1)
y = df['NObeyesdad']

In [176]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, train_size=0.8, random_state=123456
)

In [177]:
## 1. Logistic Regression
from sklearn.linear_model import LogisticRegressionCV
def create_model_logistic_regression():
    model = LogisticRegressionCV()
    model.fit(x_train, y_train)
    return model

In [178]:
## 2. KNN
from sklearn.neighbors import KNeighborsClassifier
def create_knn_model():
    model = KNeighborsClassifier(n_neighbors=5)
    model.fit(x_train, y_train)
    return model

In [179]:
## 3. SVM
from sklearn.svm import SVC
def create_svm_model():
    model = SVC()
    model.fit(x_train, y_train)
    return model

In [180]:
## 4. Decision Tree
from sklearn.tree import DecisionTreeClassifier
def create_decision_tree_model():
    model = DecisionTreeClassifier(max_depth=10)
    model.fit(x_train, y_train)
    return model

In [181]:
## 5. Random Forest
from sklearn.ensemble import RandomForestClassifier
def create_random_forest_model():
    model = RandomForestClassifier(n_estimators=100, max_depth=10)
    model.fit(x_train, y_train)
    return model

In [182]:
## 6. AdaBoost
from sklearn.ensemble import AdaBoostClassifier
def create_adaboost_model():
    model = AdaBoostClassifier(n_estimators=35, learning_rate=0.2)
    model.fit(x_train, y_train)
    return model

In [183]:
## 7. CatBoost
from catboost import CatBoostClassifier
def create_catboost_model():
    model = CatBoostClassifier(learning_rate=0.2)
    model.fit(x_train, y_train)
    return model

In [184]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
def evaluate_model_on_test_data(model):
    y_pred = model.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average="macro")
    recall = recall_score(y_test, y_pred, average="macro")
    f1 = f1_score(y_test, y_pred, average="macro")
    return f"{accuracy:.2f}", f"{precision:.2f}", f"{recall:.2f}", f"{f1:.2f}"

In [185]:
models = []
models.append({"name": "Logistic Regression", "model": create_model_logistic_regression()})
models.append({"name": "KNN", "model": create_knn_model()})
models.append({"name": "SVM", "model": create_svm_model()})
models.append({"name": "Decision Tree", "model": create_decision_tree_model()})
models.append({"name": "Random Forest", "model": create_random_forest_model()})
models.append({"name": "AdaBoost", "model": create_adaboost_model()})
models.append({"name": "CatBoost", "model": create_catboost_model()})

0:	learn: 1.4906966	total: 21.9ms	remaining: 21.9s
1:	learn: 1.2596826	total: 41.2ms	remaining: 20.6s
2:	learn: 1.0950704	total: 57.1ms	remaining: 19s
3:	learn: 0.9609402	total: 72.2ms	remaining: 18s
4:	learn: 0.8788505	total: 82.4ms	remaining: 16.4s
5:	learn: 0.8133836	total: 93.7ms	remaining: 15.5s
6:	learn: 0.7578608	total: 105ms	remaining: 14.9s
7:	learn: 0.6965005	total: 115ms	remaining: 14.3s
8:	learn: 0.6513946	total: 125ms	remaining: 13.7s
9:	learn: 0.6168346	total: 135ms	remaining: 13.4s
10:	learn: 0.5905076	total: 145ms	remaining: 13.1s
11:	learn: 0.5507823	total: 156ms	remaining: 12.8s
12:	learn: 0.5062634	total: 166ms	remaining: 12.6s
13:	learn: 0.4812385	total: 176ms	remaining: 12.4s
14:	learn: 0.4530943	total: 185ms	remaining: 12.1s
15:	learn: 0.4367700	total: 196ms	remaining: 12s
16:	learn: 0.4134987	total: 205ms	remaining: 11.8s
17:	learn: 0.3898149	total: 215ms	remaining: 11.7s
18:	learn: 0.3673923	total: 225ms	remaining: 11.6s
19:	learn: 0.3538880	total: 235ms	remaining: 11.5s
20:	learn: 0.3459061	total: 247ms	remaining: 11.5s
21:	learn: 0.3362051	total: 257ms	remaining: 11.4s
22:	learn: 0.3234548	total: 267ms	remaining: 11.4s
23:	learn: 0.3100311	total: 278ms	remaining: 11.3s
24:	learn: 0.3046141	total: 288ms	remaining: 11.2s
25:	learn: 0.2947327	total: 307ms	remaining: 11.5s
26:	learn: 0.2831445	total: 317ms	remaining: 11.4s
27:	learn: 0.2757865	total: 327ms	remaining: 11.4s
28:	learn: 0.2695709	total: 337ms	remaining: 11.3s
29:	learn: 0.2646415	total: 348ms	remaining: 11.3s
30:	learn: 0.2529231	total: 357ms	remaining: 11.2s
31:	learn: 0.2484826	total: 368ms	remaining: 11.1s
32:	learn: 0.2436789	total: 378ms	remaining: 11.1s
33:	learn: 0.2396715	total: 388ms	remaining: 11s
34:	learn: 0.2362985	total: 398ms	remaining: 11s
35:	learn: 0.2302002	total: 407ms	remaining: 10.9s
36:	learn: 0.2223320	total: 417ms	remaining: 10.9s
37:	learn: 0.2199914	total: 428ms	remaining: 10.8s
38:	learn: 0.2141111	total: 437ms	remaining: 10.8s
39:	learn: 0.2080510	total: 447ms	remaining: 10.7s
40:	learn: 0.2026021	total: 458ms	remaining: 10.7s
41:	learn: 0.2002495	total: 467ms	remaining: 10.7s
42:	learn: 0.1967858	total: 477ms	remaining: 10.6s
43:	learn: 0.1940805	total: 487ms	remaining: 10.6s
44:	learn: 0.1914707	total: 496ms	remaining: 10.5s
45:	learn: 0.1853353	total: 505ms	remaining: 10.5s
46:	learn: 0.1835664	total: 515ms	remaining: 10.4s
47:	learn: 0.1789179	total: 525ms	remaining: 10.4s
48:	learn: 0.1741808	total: 535ms	remaining: 10.4s
49:	learn: 0.1708679	total: 544ms	remaining: 10.3s
50:	learn: 0.1665754	total: 554ms	remaining: 10.3s
51:	learn: 0.1644777	total: 564ms	remaining: 10.3s
52:	learn: 0.1594381	total: 573ms	remaining: 10.2s
53:	learn: 0.1572280	total: 582ms	remaining: 10.2s
54:	learn: 0.1559047	total: 592ms	remaining: 10.2s
55:	learn: 0.1520274	total: 601ms	remaining: 10.1s
56:	learn: 0.1505790	total: 611ms	remaining: 10.1s
57:	learn: 0.1476385	total: 621ms	remaining: 10.1s
58:	learn: 0.1446183	total: 630ms	remaining: 10s
59:	learn: 0.1413418	total: 640ms	remaining: 10s
60:	learn: 0.1391361	total: 649ms	remaining: 9.99s
61:	learn: 0.1375579	total: 659ms	remaining: 9.97s
62:	learn: 0.1364339	total: 668ms	remaining: 9.93s
63:	learn: 0.1348718	total: 678ms	remaining: 9.91s
64:	learn: 0.1334841	total: 688ms	remaining: 9.89s
65:	learn: 0.1319160	total: 698ms	remaining: 9.88s
66:	learn: 0.1294458	total: 709ms	remaining: 9.87s
67:	learn: 0.1255056	total: 718ms	remaining: 9.85s
68:	learn: 0.1241937	total: 728ms	remaining: 9.82s
69:	learn: 0.1216612	total: 737ms	remaining: 9.8s
70:	learn: 0.1197437	total: 747ms	remaining: 9.77s
71:	learn: 0.1170235	total: 756ms	remaining: 9.74s
72:	learn: 0.1157090	total: 766ms	remaining: 9.72s
73:	learn: 0.1145778	total: 776ms	remaining: 9.71s
74:	learn: 0.1131988	total: 786ms	remaining: 9.69s
75:	learn: 0.1105858	total: 795ms	remaining: 9.66s
76:	learn: 0.1086374	total: 805ms	remaining: 9.65s
77:	learn: 0.1072961	total: 815ms	remaining: 9.63s
78:	learn: 0.1062880	total: 824ms	remaining: 9.61s
79:	learn: 0.1049321	total: 834ms	remaining: 9.6s
80:	learn: 0.1043293	total: 845ms	remaining: 9.58s
81:	learn: 0.1034554	total: 855ms	remaining: 9.58s
82:	learn: 0.1019546	total: 865ms	remaining: 9.56s
83:	learn: 0.1008767	total: 875ms	remaining: 9.54s
84:	learn: 0.0996998	total: 886ms	remaining: 9.53s
85:	learn: 0.0986185	total: 896ms	remaining: 9.52s
86:	learn: 0.0976232	total: 906ms	remaining: 9.5s
87:	learn: 0.0961571	total: 916ms	remaining: 9.49s
88:	learn: 0.0953258	total: 927ms	remaining: 9.49s
89:	learn: 0.0940096	total: 937ms	remaining: 9.47s
90:	learn: 0.0930991	total: 947ms	remaining: 9.45s
91:	learn: 0.0905424	total: 956ms	remaining: 9.44s
92:	learn: 0.0899442	total: 966ms	remaining: 9.43s
93:	learn: 0.0886772	total: 976ms	remaining: 9.41s
94:	learn: 0.0870725	total: 985ms	remaining: 9.39s
95:	learn: 0.0862381	total: 995ms	remaining: 9.36s
96:	learn: 0.0856441	total: 1s	remaining: 9.35s
97:	learn: 0.0852160	total: 1.01s	remaining: 9.34s
98:	learn: 0.0842014	total: 1.02s	remaining: 9.31s
99:	learn: 0.0836029	total: 1.03s	remaining: 9.3s
100:	learn: 0.0825797	total: 1.04s	remaining: 9.29s
101:	learn: 0.0820399	total: 1.05s	remaining: 9.28s
102:	learn: 0.0808461	total: 1.06s	remaining: 9.26s
103:	learn: 0.0803763	total: 1.07s	remaining: 9.25s
104:	learn: 0.0796618	total: 1.08s	remaining: 9.23s
105:	learn: 0.0790862	total: 1.09s	remaining: 9.22s
106:	learn: 0.0786372	total: 1.1s	remaining: 9.2s
107:	learn: 0.0775574	total: 1.11s	remaining: 9.19s
108:	learn: 0.0768636	total: 1.12s	remaining: 9.17s
109:	learn: 0.0759968	total: 1.13s	remaining: 9.16s
110:	learn: 0.0757390	total: 1.14s	remaining: 9.15s
111:	learn: 0.0744997	total: 1.15s	remaining: 9.13s
112:	learn: 0.0740219	total: 1.16s	remaining: 9.12s
113:	learn: 0.0732730	total: 1.17s	remaining: 9.1s
114:	learn: 0.0725110	total: 1.18s	remaining: 9.08s
115:	learn: 0.0721466	total: 1.19s	remaining: 9.07s
116:	learn: 0.0712125	total: 1.2s	remaining: 9.05s
117:	learn: 0.0704931	total: 1.21s	remaining: 9.04s
118:	learn: 0.0702039	total: 1.22s	remaining: 9.02s
119:	learn: 0.0699858	total: 1.23s	remaining: 9.01s
120:	learn: 0.0692775	total: 1.24s	remaining: 8.99s
121:	learn: 0.0685995	total: 1.25s	remaining: 8.99s
122:	learn: 0.0681939	total: 1.26s	remaining: 8.98s
123:	learn: 0.0678145	total: 1.27s	remaining: 8.96s
124:	learn: 0.0675032	total: 1.28s	remaining: 8.94s
125:	learn: 0.0672233	total: 1.29s	remaining: 8.93s
126:	learn: 0.0668710	total: 1.3s	remaining: 8.91s
127:	learn: 0.0653185	total: 1.31s	remaining: 8.9s
128:	learn: 0.0642051	total: 1.32s	remaining: 8.89s
129:	learn: 0.0635877	total: 1.32s	remaining: 8.87s
130:	learn: 0.0630424	total: 1.33s	remaining: 8.86s
131:	learn: 0.0624618	total: 1.34s	remaining: 8.85s
132:	learn: 0.0620635	total: 1.35s	remaining: 8.83s
133:	learn: 0.0616671	total: 1.36s	remaining: 8.82s
134:	learn: 0.0615219	total: 1.37s	remaining: 8.8s
135:	learn: 0.0612522	total: 1.38s	remaining: 8.79s
136:	learn: 0.0605868	total: 1.39s	remaining: 8.78s
137:	learn: 0.0603882	total: 1.4s	remaining: 8.76s
138:	learn: 0.0600135	total: 1.41s	remaining: 8.75s
139:	learn: 0.0593628	total: 1.42s	remaining: 8.73s
140:	learn: 0.0589379	total: 1.43s	remaining: 8.72s
141:	learn: 0.0585852	total: 1.44s	remaining: 8.71s
142:	learn: 0.0577094	total: 1.45s	remaining: 8.69s
143:	learn: 0.0573538	total: 1.46s	remaining: 8.68s
144:	learn: 0.0567892	total: 1.47s	remaining: 8.66s
145:	learn: 0.0564615	total: 1.48s	remaining: 8.65s
146:	learn: 0.0558445	total: 1.49s	remaining: 8.64s
147:	learn: 0.0550858	total: 1.5s	remaining: 8.63s
148:	learn: 0.0548059	total: 1.51s	remaining: 8.61s
149:	learn: 0.0539611	total: 1.52s	remaining: 8.6s
150:	learn: 0.0532289	total: 1.53s	remaining: 8.59s
151:	learn: 0.0527184	total: 1.54s	remaining: 8.58s
152:	learn: 0.0523470	total: 1.55s	remaining: 8.57s
153:	learn: 0.0518947	total: 1.56s	remaining: 8.55s
154:	learn: 0.0515738	total: 1.57s	remaining: 8.54s
155:	learn: 0.0512824	total: 1.58s	remaining: 8.53s
156:	learn: 0.0509267	total: 1.58s	remaining: 8.51s
157:	learn: 0.0507068	total: 1.59s	remaining: 8.5s
158:	learn: 0.0504923	total: 1.61s	remaining: 8.5s
159:	learn: 0.0499171	total: 1.62s	remaining: 8.5s
160:	learn: 0.0495726	total: 1.63s	remaining: 8.48s
161:	learn: 0.0493992	total: 1.64s	remaining: 8.47s
162:	learn: 0.0491893	total: 1.65s	remaining: 8.46s
163:	learn: 0.0490112	total: 1.66s	remaining: 8.45s
164:	learn: 0.0487213	total: 1.67s	remaining: 8.44s
165:	learn: 0.0483511	total: 1.68s	remaining: 8.42s
166:	learn: 0.0480096	total: 1.69s	remaining: 8.41s
167:	learn: 0.0473034	total: 1.7s	remaining: 8.39s
168:	learn: 0.0470972	total: 1.7s	remaining: 8.38s
169:	learn: 0.0469059	total: 1.71s	remaining: 8.37s
170:	learn: 0.0465997	total: 1.72s	remaining: 8.36s
171:	learn: 0.0463195	total: 1.73s	remaining: 8.35s
172:	learn: 0.0459166	total: 1.74s	remaining: 8.33s
173:	learn: 0.0456712	total: 1.75s	remaining: 8.32s
174:	learn: 0.0450429	total: 1.76s	remaining: 8.31s
175:	learn: 0.0448302	total: 1.77s	remaining: 8.3s
176:	learn: 0.0446131	total: 1.78s	remaining: 8.29s
177:	learn: 0.0439429	total: 1.79s	remaining: 8.28s
178:	learn: 0.0436517	total: 1.8s	remaining: 8.26s
179:	learn: 0.0434668	total: 1.81s	remaining: 8.25s
180:	learn: 0.0432830	total: 1.82s	remaining: 8.24s
181:	learn: 0.0431848	total: 1.83s	remaining: 8.23s
182:	learn: 0.0427397	total: 1.84s	remaining: 8.23s
183:	learn: 0.0424873	total: 1.85s	remaining: 8.22s
184:	learn: 0.0421213	total: 1.86s	remaining: 8.21s
185:	learn: 0.0419727	total: 1.87s	remaining: 8.2s
186:	learn: 0.0418443	total: 1.88s	remaining: 8.19s
187:	learn: 0.0417403	total: 1.89s	remaining: 8.18s
188:	learn: 0.0415855	total: 1.9s	remaining: 8.16s
189:	learn: 0.0412916	total: 1.91s	remaining: 8.15s
190:	learn: 0.0408224	total: 1.92s	remaining: 8.14s
191:	learn: 0.0405296	total: 1.93s	remaining: 8.13s
192:	learn: 0.0404544	total: 1.94s	remaining: 8.12s
193:	learn: 0.0400982	total: 1.95s	remaining: 8.1s
194:	learn: 0.0399435	total: 1.96s	remaining: 8.09s
195:	learn: 0.0398648	total: 1.97s	remaining: 8.08s
196:	learn: 0.0395767	total: 1.98s	remaining: 8.07s
197:	learn: 0.0391778	total: 1.99s	remaining: 8.06s
198:	learn: 0.0390418	total: 2s	remaining: 8.04s
199:	learn: 0.0387500	total: 2.01s	remaining: 8.03s
200:	learn: 0.0386283	total: 2.02s	remaining: 8.02s
201:	learn: 0.0382854	total: 2.03s	remaining: 8.01s
202:	learn: 0.0379777	total: 2.04s	remaining: 8s
203:	learn: 0.0378188	total: 2.05s	remaining: 7.99s
204:	learn: 0.0376183	total: 2.06s	remaining: 7.98s
205:	learn: 0.0372346	total: 2.07s	remaining: 7.97s
206:	learn: 0.0369983	total: 2.08s	remaining: 7.96s
207:	learn: 0.0368205	total: 2.09s	remaining: 7.95s
208:	learn: 0.0366495	total: 2.1s	remaining: 7.94s
209:	learn: 0.0363323	total: 2.11s	remaining: 7.92s
210:	learn: 0.0361259	total: 2.12s	remaining: 7.91s
211:	learn: 0.0360055	total: 2.13s	remaining: 7.9s
212:	learn: 0.0359565	total: 2.14s	remaining: 7.89s
213:	learn: 0.0357674	total: 2.15s	remaining: 7.88s
214:	learn: 0.0354690	total: 2.16s	remaining: 7.87s
215:	learn: 0.0353810	total: 2.17s	remaining: 7.86s
216:	learn: 0.0351841	total: 2.17s	remaining: 7.85s
217:	learn: 0.0350556	total: 2.19s	remaining: 7.84s
218:	learn: 0.0348433	total: 2.19s	remaining: 7.83s
219:	learn: 0.0344003	total: 2.21s	remaining: 7.82s
220:	learn: 0.0342367	total: 2.21s	remaining: 7.81s
221:	learn: 0.0341109	total: 2.23s	remaining: 7.8s
222:	learn: 0.0338881	total: 2.23s	remaining: 7.79s
223:	learn: 0.0335450	total: 2.24s	remaining: 7.78s
224:	learn: 0.0334206	total: 2.25s	remaining: 7.76s
225:	learn: 0.0332336	total: 2.26s	remaining: 7.75s
226:	learn: 0.0331351	total: 2.27s	remaining: 7.74s
227:	learn: 0.0330584	total: 2.28s	remaining: 7.73s
228:	learn: 0.0328840	total: 2.29s	remaining: 7.72s
229:	learn: 0.0327439	total: 2.3s	remaining: 7.71s
230:	learn: 0.0326719	total: 2.31s	remaining: 7.7s
231:	learn: 0.0324768	total: 2.32s	remaining: 7.69s
232:	learn: 0.0322683	total: 2.33s	remaining: 7.67s
233:	learn: 0.0321707	total: 2.34s	remaining: 7.67s
234:	learn: 0.0321082	total: 2.35s	remaining: 7.65s
235:	learn: 0.0318829	total: 2.36s	remaining: 7.64s
236:	learn: 0.0317555	total: 2.37s	remaining: 7.63s
237:	learn: 0.0316652	total: 2.38s	remaining: 7.62s
238:	learn: 0.0315369	total: 2.39s	remaining: 7.61s
239:	learn: 0.0313416	total: 2.4s	remaining: 7.6s
240:	learn: 0.0312307	total: 2.41s	remaining: 7.58s
241:	learn: 0.0311442	total: 2.42s	remaining: 7.57s
242:	learn: 0.0309898	total: 2.43s	remaining: 7.56s
243:	learn: 0.0309160	total: 2.44s	remaining: 7.55s
244:	learn: 0.0305956	total: 2.45s	remaining: 7.54s
245:	learn: 0.0304576	total: 2.46s	remaining: 7.54s
246:	learn: 0.0304013	total: 2.47s	remaining: 7.52s
247:	learn: 0.0302010	total: 2.48s	remaining: 7.51s
248:	learn: 0.0300274	total: 2.49s	remaining: 7.5s
249:	learn: 0.0298959	total: 2.5s	remaining: 7.49s
250:	learn: 0.0297704	total: 2.5s	remaining: 7.48s
251:	learn: 0.0297118	total: 2.52s	remaining: 7.47s
252:	learn: 0.0295703	total: 2.52s	remaining: 7.46s
253:	learn: 0.0294230	total: 2.54s	remaining: 7.45s
254:	learn: 0.0292840	total: 2.54s	remaining: 7.44s
255:	learn: 0.0290789	total: 2.55s	remaining: 7.42s
256:	learn: 0.0289675	total: 2.56s	remaining: 7.41s
257:	learn: 0.0288987	total: 2.57s	remaining: 7.4s
258:	learn: 0.0286502	total: 2.58s	remaining: 7.39s
259:	learn: 0.0285151	total: 2.59s	remaining: 7.38s
260:	learn: 0.0284074	total: 2.6s	remaining: 7.37s
261:	learn: 0.0283280	total: 2.61s	remaining: 7.36s
262:	learn: 0.0282069	total: 2.62s	remaining: 7.36s
263:	learn: 0.0280250	total: 2.63s	remaining: 7.34s
264:	learn: 0.0278953	total: 2.64s	remaining: 7.33s
265:	learn: 0.0278204	total: 2.65s	remaining: 7.33s
266:	learn: 0.0277539	total: 2.66s	remaining: 7.31s
267:	learn: 0.0276825	total: 2.67s	remaining: 7.3s
268:	learn: 0.0276114	total: 2.68s	remaining: 7.29s
269:	learn: 0.0275358	total: 2.69s	remaining: 7.28s
270:	learn: 0.0273773	total: 2.7s	remaining: 7.27s
271:	learn: 0.0273109	total: 2.71s	remaining: 7.26s
272:	learn: 0.0272048	total: 2.72s	remaining: 7.25s
273:	learn: 0.0270906	total: 2.73s	remaining: 7.24s
274:	learn: 0.0270280	total: 2.74s	remaining: 7.23s
275:	learn: 0.0269631	total: 2.75s	remaining: 7.22s
276:	learn: 0.0269292	total: 2.76s	remaining: 7.21s
277:	learn: 0.0267424	total: 2.77s	remaining: 7.2s
278:	learn: 0.0266757	total: 2.78s	remaining: 7.19s
279:	learn: 0.0265621	total: 2.79s	remaining: 7.18s
280:	learn: 0.0264335	total: 2.8s	remaining: 7.17s
281:	learn: 0.0263716	total: 2.81s	remaining: 7.16s
282:	learn: 0.0263218	total: 2.82s	remaining: 7.14s
283:	learn: 0.0262620	total: 2.83s	remaining: 7.13s
284:	learn: 0.0261097	total: 2.84s	remaining: 7.12s
285:	learn: 0.0260175	total: 2.85s	remaining: 7.11s
286:	learn: 0.0259529	total: 2.86s	remaining: 7.1s
287:	learn: 0.0258879	total: 2.87s	remaining: 7.09s
288:	learn: 0.0257146	total: 2.88s	remaining: 7.08s
289:	learn: 0.0255251	total: 2.89s	remaining: 7.07s
290:	learn: 0.0254394	total: 2.9s	remaining: 7.06s
291:	learn: 0.0253408	total: 2.91s	remaining: 7.05s
292:	learn: 0.0252074	total: 2.92s	remaining: 7.04s
293:	learn: 0.0250748	total: 2.93s	remaining: 7.03s
294:	learn: 0.0249716	total: 2.94s	remaining: 7.02s
295:	learn: 0.0249178	total: 2.94s	remaining: 7.01s
296:	learn: 0.0248361	total: 2.96s	remaining: 7s
297:	learn: 0.0247121	total: 2.96s	remaining: 6.98s
298:	learn: 0.0245728	total: 2.97s	remaining: 6.97s
299:	learn: 0.0244376	total: 2.98s	remaining: 6.96s
300:	learn: 0.0244127	total: 2.99s	remaining: 6.95s
301:	learn: 0.0243225	total: 3s	remaining: 6.94s
302:	learn: 0.0242114	total: 3.01s	remaining: 6.93s
303:	learn: 0.0241632	total: 3.02s	remaining: 6.92s
304:	learn: 0.0240378	total: 3.03s	remaining: 6.91s
305:	learn: 0.0239655	total: 3.04s	remaining: 6.9s
306:	learn: 0.0239004	total: 3.05s	remaining: 6.89s
307:	learn: 0.0238469	total: 3.06s	remaining: 6.88s
308:	learn: 0.0237611	total: 3.07s	remaining: 6.87s
309:	learn: 0.0236831	total: 3.08s	remaining: 6.86s
310:	learn: 0.0236468	total: 3.09s	remaining: 6.84s
311:	learn: 0.0234057	total: 3.1s	remaining: 6.83s
312:	learn: 0.0233028	total: 3.11s	remaining: 6.82s
313:	learn: 0.0231759	total: 3.12s	remaining: 6.81s
314:	learn: 0.0231566	total: 3.13s	remaining: 6.8s
315:	learn: 0.0230521	total: 3.14s	remaining: 6.79s
316:	learn: 0.0229942	total: 3.15s	remaining: 6.78s
317:	learn: 0.0228482	total: 3.15s	remaining: 6.77s
318:	learn: 0.0227815	total: 3.17s	remaining: 6.76s
319:	learn: 0.0227470	total: 3.17s	remaining: 6.75s
320:	learn: 0.0227054	total: 3.18s	remaining: 6.74s
321:	learn: 0.0226629	total: 3.19s	remaining: 6.73s
322:	learn: 0.0225402	total: 3.2s	remaining: 6.72s
323:	learn: 0.0224876	total: 3.21s	remaining: 6.71s
324:	learn: 0.0224530	total: 3.22s	remaining: 6.7s
325:	learn: 0.0223425	total: 3.23s	remaining: 6.69s
326:	learn: 0.0222156	total: 3.24s	remaining: 6.68s
327:	learn: 0.0221107	total: 3.25s	remaining: 6.67s
328:	learn: 0.0220363	total: 3.26s	remaining: 6.66s
329:	learn: 0.0219986	total: 3.27s	remaining: 6.65s
330:	learn: 0.0219420	total: 3.28s	remaining: 6.63s
331:	learn: 0.0218779	total: 3.29s	remaining: 6.63s
332:	learn: 0.0217783	total: 3.3s	remaining: 6.61s
333:	learn: 0.0217021	total: 3.31s	remaining: 6.6s
334:	learn: 0.0216440	total: 3.32s	remaining: 6.59s
335:	learn: 0.0215939	total: 3.33s	remaining: 6.58s
336:	learn: 0.0215446	total: 3.34s	remaining: 6.57s
337:	learn: 0.0215172	total: 3.35s	remaining: 6.56s
338:	learn: 0.0214711	total: 3.36s	remaining: 6.55s
339:	learn: 0.0213052	total: 3.37s	remaining: 6.54s
340:	learn: 0.0211657	total: 3.38s	remaining: 6.53s
341:	learn: 0.0210806	total: 3.39s	remaining: 6.52s
342:	learn: 0.0210361	total: 3.4s	remaining: 6.51s
343:	learn: 0.0209739	total: 3.41s	remaining: 6.5s
344:	learn: 0.0209015	total: 3.42s	remaining: 6.49s
345:	learn: 0.0208287	total: 3.43s	remaining: 6.48s
346:	learn: 0.0207627	total: 3.44s	remaining: 6.47s
347:	learn: 0.0207244	total: 3.45s	remaining: 6.46s
348:	learn: 0.0206054	total: 3.46s	remaining: 6.45s
349:	learn: 0.0205111	total: 3.47s	remaining: 6.44s
350:	learn: 0.0204528	total: 3.48s	remaining: 6.43s
351:	learn: 0.0203433	total: 3.49s	remaining: 6.42s
352:	learn: 0.0201865	total: 3.5s	remaining: 6.41s
353:	learn: 0.0200893	total: 3.51s	remaining: 6.4s
354:	learn: 0.0200398	total: 3.52s	remaining: 6.39s
355:	learn: 0.0199853	total: 3.52s	remaining: 6.38s
356:	learn: 0.0199391	total: 3.54s	remaining: 6.37s
357:	learn: 0.0198356	total: 3.54s	remaining: 6.36s
358:	learn: 0.0197621	total: 3.55s	remaining: 6.35s
359:	learn: 0.0197166	total: 3.56s	remaining: 6.34s
360:	learn: 0.0196663	total: 3.57s	remaining: 6.33s
361:	learn: 0.0196063	total: 3.58s	remaining: 6.32s
362:	learn: 0.0194468	total: 3.59s	remaining: 6.31s
363:	learn: 0.0193929	total: 3.6s	remaining: 6.3s
364:	learn: 0.0192835	total: 3.61s	remaining: 6.29s
365:	learn: 0.0192526	total: 3.62s	remaining: 6.28s
366:	learn: 0.0191576	total: 3.63s	remaining: 6.27s
367:	learn: 0.0191291	total: 3.64s	remaining: 6.26s
368:	learn: 0.0190487	total: 3.65s	remaining: 6.25s
369:	learn: 0.0189304	total: 3.66s	remaining: 6.24s
370:	learn: 0.0188398	total: 3.67s	remaining: 6.23s
371:	learn: 0.0187011	total: 3.68s	remaining: 6.21s
372:	learn: 0.0186284	total: 3.69s	remaining: 6.2s
373:	learn: 0.0186013	total: 3.7s	remaining: 6.19s
374:	learn: 0.0185837	total: 3.71s	remaining: 6.18s
375:	learn: 0.0185103	total: 3.72s	remaining: 6.17s
376:	learn: 0.0183548	total: 3.73s	remaining: 6.16s
377:	learn: 0.0182630	total: 3.74s	remaining: 6.15s
378:	learn: 0.0181934	total: 3.75s	remaining: 6.14s
379:	learn: 0.0181564	total: 3.76s	remaining: 6.13s
380:	learn: 0.0181193	total: 3.77s	remaining: 6.12s
381:	learn: 0.0180806	total: 3.78s	remaining: 6.11s
382:	learn: 0.0180467	total: 3.79s	remaining: 6.1s
383:	learn: 0.0179657	total: 3.8s	remaining: 6.09s
384:	learn: 0.0179086	total: 3.81s	remaining: 6.08s
385:	learn: 0.0178208	total: 3.82s	remaining: 6.07s
386:	learn: 0.0177621	total: 3.83s	remaining: 6.06s
387:	learn: 0.0177284	total: 3.84s	remaining: 6.05s

In [186]:
# Evaluate models
for info in models:
    accuracy,precision,recall,f1=evaluate_model_on_test_data(info["model"])
    info['accuracy']=accuracy
    info["precision"] = precision
    info["recall"] = recall
    info["f1"] = f1
    
# report
df_evaluation_report_test = pd.DataFrame(models, columns=["name", "accuracy", "precision", "recall", "f1"])
df_evaluation_report_test

                  name accuracy precision recall    f1
0  Logistic Regression     0.80      0.78   0.78  0.78
1                  KNN     0.84      0.82   0.83  0.82
2                  SVM     0.49      0.51   0.51  0.49
3        Decision Tree     0.95      0.95   0.95  0.95
4        Random Forest     0.93      0.93   0.93  0.93
5             AdaBoost     0.46      0.32   0.41  0.32
6             CatBoost     0.96      0.96   0.96  0.96

# Que.5

In [ ]:
The heart.csv dataset contains clinical and demographic information of patients. 
The objective is to analyze these medical attributes and predict whether a patient has heart disease.

Dataset Description:
Each record represents a patient with the following attributes:
Age
Sex
ChestPainType
RestingBP (Resting Blood Pressure)
Cholesterol
FastingBS (Fasting Blood Sugar)
RestingECG
MaxHR (Maximum Heart Rate Achieved)
ExerciseAngina
Oldpeak (ST depression)
ST_Slope
HeartDisease

Build Logistic Regression, KNN, SVM, Decision Tree, Random Forest, AdaBoost, CatBoost models that can predict the presence or absence of heart disease based on patient health indicators.
Calculate Accuracy by confusion matrix, Calculate accuracy score, precision score, recall score, f1 score.
Also Prepare summary of all models & Select best of them.

In [204]:
df = pd.read_csv('heart.csv')
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [188]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [189]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [190]:
df.corr()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
age,1.000000,-0.098447,-0.068653,0.279351,0.213678,0.121308,-0.116211,-0.398522,0.096801,0.210013,-0.168814,0.276326,0.068001,-0.225439
sex,-0.098447,1.000000,-0.049353,-0.056769,-0.197912,0.045032,-0.058196,-0.044020,0.141664,0.096093,-0.030711,0.118261,0.210041,-0.280937
cp,-0.068653,-0.049353,1.000000,0.047608,-0.076904,0.094444,0.044421,0.295762,-0.394280,-0.149230,0.119717,-0.181053,-0.161736,0.433798
trestbps,0.279351,-0.056769,0.047608,1.000000,0.123174,0.177531,-0.114103,-0.046698,0.067616,0.193216,-0.121475,0.101389,0.062210,-0.144931
chol,0.213678,-0.197912,-0.076904,0.123174,1.000000,0.013294,-0.151040,-0.009940,0.067023,0.053952,-0.004038,0.070511,0.098803,-0.085239
fbs,0.121308,0.045032,0.094444,0.177531,0.013294,1.000000,-0.084189,-0.008567,0.025665,0.005747,-0.059894,0.137979,-0.032019,-0.028046
restecg,-0.116211,-0.058196,0.044421,-0.114103,-0.151040,-0.084189,1.000000,0.044123,-0.070733,-0.058770,0.093045,-0.072042,-0.011981,0.137230
thalach,-0.398522,-0.044020,0.295762,-0.046698,-0.009940,-0.008567,0.044123,1.000000,-0.378812,-0.344187,0.386784,-0.213177,-0.096439,0.421741
exang,0.096801,0.141664,-0.394280,0.067616,0.067023,0.025665,-0.070733,-0.378812,1.000000,0.288223,-0.257748,0.115739,0.206754,-0.436757
oldpeak,0.210013,0.096093,-0.149230,0.193216,0.053952,0.005747,-0.058770,-0.344187,0.288223,1.000000,-0.577537,0.222682,0.210244,-0.430696
slope,-0.168814,-0.030711,0.119717,-0.121475,-0.004038,-0.059894,0.093045,0.386784,-0.257748,-0.577537,1.000000,-0.080155,-0.104764,0.345877
ca,0.276326,0.118261,-0.181053,0.101389,0.070511,0.137979,-0.072042,-0.213177,0.115739,0.222682,-0.080155,1.000000,0.151832,-0.391724
thal,0.068001,0.210041,-0.161736,0.062210,0.098803,-0.032019,-0.011981,-0.096439,0.206754,0.210244,-0.104764,0.151832,1.000000,-0.344029
target,-0.225439,-0.280937,0.433798,-0.144931,-0.085239,-0.028046,0.137230,0.421741,-0.436757,-0.430696,0.345877,-0.391724,-0.344029,1.000000

In [205]:
df.drop(['exang','oldpeak','ca','thal'],axis=1,inplace=True)

In [206]:
x = df.drop('target', axis=1)
y = df['target']

In [207]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    x, y, train_size=0.8, random_state=123456
)

In [208]:
## 1. Logistic Regression
from sklearn.linear_model import LogisticRegressionCV
def create_model_logistic_regression():
    model = LogisticRegressionCV()
    model.fit(x_train, y_train)
    return model

In [209]:
## 2. KNN
from sklearn.neighbors import KNeighborsClassifier
def create_knn_model():
    model = KNeighborsClassifier(n_neighbors=5)
    model.fit(x_train, y_train)
    return model

In [210]:
## 3. SVM
from sklearn.svm import SVC
def create_svm_model():
    model = SVC()
    model.fit(x_train, y_train)
    return model

In [211]:
## 4. Decision Tree
from sklearn.tree import DecisionTreeClassifier
def create_decision_tree_model():
    model = DecisionTreeClassifier(max_depth=10)
    model.fit(x_train, y_train)
    return model

In [212]:
## 5. Random Forest
from sklearn.ensemble import RandomForestClassifier
def create_random_forest_model():
    model = RandomForestClassifier(n_estimators=100, max_depth=10)
    model.fit(x_train, y_train)
    return model

In [213]:
## 6. AdaBoost
from sklearn.ensemble import AdaBoostClassifier
def create_adaboost_model():
    model = AdaBoostClassifier(n_estimators=35, learning_rate=0.2)
    model.fit(x_train, y_train)
    return model

In [214]:
## 7. CatBoost
from catboost import CatBoostClassifier
def create_catboost_model():
    model = CatBoostClassifier(learning_rate=0.2)
    model.fit(x_train, y_train)
    return model

In [215]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
def evaluate_model_on_test_data(model):
    y_pred = model.predict(x_test)
    accuracy = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average="macro")
    recall = recall_score(y_test, y_pred, average="macro")
    f1 = f1_score(y_test, y_pred, average="macro")
    return f"{accuracy:.2f}", f"{precision:.2f}", f"{recall:.2f}", f"{f1:.2f}"

In [216]:
models = []
models.append({"name": "Logistic Regression", "model": create_model_logistic_regression()})
models.append({"name": "KNN", "model": create_knn_model()})
models.append({"name": "SVM", "model": create_svm_model()})
models.append({"name": "Decision Tree", "model": create_decision_tree_model()})
models.append({"name": "Random Forest", "model": create_random_forest_model()})
models.append({"name": "AdaBoost", "model": create_adaboost_model()})
models.append({"name": "CatBoost", "model": create_catboost_model()})

0:	learn: 0.5809024	total: 13.1ms	remaining: 13.1s
1:	learn: 0.5056858	total: 16.4ms	remaining: 8.19s
2:	learn: 0.4630929	total: 19.3ms	remaining: 6.43s
3:	learn: 0.4371861	total: 22.1ms	remaining: 5.5s
4:	learn: 0.4045765	total: 24.4ms	remaining: 4.86s
5:	learn: 0.3731193	total: 27.1ms	remaining: 4.49s
6:	learn: 0.3604370	total: 29.9ms	remaining: 4.24s
7:	learn: 0.3461555	total: 33.6ms	remaining: 4.16s
8:	learn: 0.3259722	total: 35.9ms	remaining: 3.95s
9:	learn: 0.3075194	total: 38.3ms	remaining: 3.79s
10:	learn: 0.2901277	total: 40.7ms	remaining: 3.66s
11:	learn: 0.2791497	total: 43ms	remaining: 3.54s
12:	learn: 0.2671614	total: 45.6ms	remaining: 3.46s
13:	learn: 0.2566785	total: 47.9ms	remaining: 3.37s
14:	learn: 0.2465627	total: 49.9ms	remaining: 3.28s
15:	learn: 0.2425916	total: 52.3ms	remaining: 3.21s
16:	learn: 0.2309267	total: 55.9ms	remaining: 3.23s
17:	learn: 0.2288583	total: 59.6ms	remaining: 3.25s
18:	learn: 0.2253356	total: 62.5ms	remaining: 3.23s
19:	learn: 0.2197701	total: 66.2ms	remaining: 3.24s
20:	learn: 0.2129869	total: 70.3ms	remaining: 3.28s
21:	learn: 0.2078134	total: 73ms	remaining: 3.25s
22:	learn: 0.2022317	total: 75.4ms	remaining: 3.2s
23:	learn: 0.1978975	total: 78.7ms	remaining: 3.2s
24:	learn: 0.1941790	total: 82ms	remaining: 3.2s
25:	learn: 0.1850763	total: 85.2ms	remaining: 3.19s
26:	learn: 0.1738599	total: 88.4ms	remaining: 3.18s
27:	learn: 0.1715884	total: 92.9ms	remaining: 3.22s
28:	learn: 0.1664506	total: 95.5ms	remaining: 3.2s
29:	learn: 0.1570931	total: 97.8ms	remaining: 3.16s
30:	learn: 0.1515446	total: 100ms	remaining: 3.13s
31:	learn: 0.1471434	total: 103ms	remaining: 3.12s
32:	learn: 0.1434132	total: 107ms	remaining: 3.12s
33:	learn: 0.1380306	total: 109ms	remaining: 3.11s
34:	learn: 0.1343322	total: 112ms	remaining: 3.09s
35:	learn: 0.1318594	total: 115ms	remaining: 3.08s
36:	learn: 0.1241538	total: 118ms	remaining: 3.06s
37:	learn: 0.1187880	total: 120ms	remaining: 3.03s
38:	learn: 0.1174797	total: 122ms	remaining: 3.01s
39:	learn: 0.1151466	total: 125ms	remaining: 2.99s
40:	learn: 0.1130041	total: 128ms	remaining: 2.99s
41:	learn: 0.1089012	total: 131ms	remaining: 2.99s
42:	learn: 0.1067973	total: 133ms	remaining: 2.96s
43:	learn: 0.1029199	total: 136ms	remaining: 2.95s
44:	learn: 0.0993006	total: 138ms	remaining: 2.92s
45:	learn: 0.0955022	total: 140ms	remaining: 2.9s
46:	learn: 0.0928111	total: 143ms	remaining: 2.9s
47:	learn: 0.0916622	total: 146ms	remaining: 2.9s
48:	learn: 0.0886806	total: 150ms	remaining: 2.91s
49:	learn: 0.0862890	total: 153ms	remaining: 2.91s
50:	learn: 0.0834024	total: 156ms	remaining: 2.9s
51:	learn: 0.0802196	total: 158ms	remaining: 2.89s
52:	learn: 0.0772933	total: 161ms	remaining: 2.88s
53:	learn: 0.0747762	total: 164ms	remaining: 2.87s
54:	learn: 0.0730830	total: 167ms	remaining: 2.86s
55:	learn: 0.0710449	total: 170ms	remaining: 2.86s
56:	learn: 0.0699008	total: 172ms	remaining: 2.85s
57:	learn: 0.0674324	total: 175ms	remaining: 2.84s
58:	learn: 0.0649039	total: 177ms	remaining: 2.83s
59:	learn: 0.0634240	total: 182ms	remaining: 2.85s
60:	learn: 0.0616599	total: 186ms	remaining: 2.87s
61:	learn: 0.0612380	total: 192ms	remaining: 2.91s
62:	learn: 0.0596759	total: 197ms	remaining: 2.93s
63:	learn: 0.0581751	total: 202ms	remaining: 2.96s
64:	learn: 0.0567423	total: 207ms	remaining: 2.98s
65:	learn: 0.0555170	total: 212ms	remaining: 3s
66:	learn: 0.0540828	total: 224ms	remaining: 3.12s
67:	learn: 0.0520357	total: 238ms	remaining: 3.25s
68:	learn: 0.0504634	total: 250ms	remaining: 3.38s
69:	learn: 0.0493601	total: 257ms	remaining: 3.42s
70:	learn: 0.0476272	total: 262ms	remaining: 3.43s
71:	learn: 0.0465650	total: 266ms	remaining: 3.42s
72:	learn: 0.0458006	total: 269ms	remaining: 3.42s
73:	learn: 0.0447762	total: 273ms	remaining: 3.42s
74:	learn: 0.0438833	total: 276ms	remaining: 3.41s
75:	learn: 0.0429868	total: 279ms	remaining: 3.39s
76:	learn: 0.0420115	total: 283ms	remaining: 3.39s
77:	learn: 0.0414087	total: 286ms	remaining: 3.38s
78:	learn: 0.0406883	total: 289ms	remaining: 3.36s
79:	learn: 0.0402804	total: 292ms	remaining: 3.36s
80:	learn: 0.0396737	total: 296ms	remaining: 3.36s
81:	learn: 0.0389552	total: 299ms	remaining: 3.35s
82:	learn: 0.0380889	total: 302ms	remaining: 3.34s
83:	learn: 0.0373777	total: 306ms	remaining: 3.33s
84:	learn: 0.0367053	total: 310ms	remaining: 3.33s
85:	learn: 0.0357898	total: 313ms	remaining: 3.32s
86:	learn: 0.0351609	total: 316ms	remaining: 3.31s
87:	learn: 0.0341929	total: 319ms	remaining: 3.31s
88:	learn: 0.0334436	total: 322ms	remaining: 3.3s
89:	learn: 0.0325201	total: 325ms	remaining: 3.29s
90:	learn: 0.0318133	total: 328ms	remaining: 3.27s
91:	learn: 0.0309972	total: 331ms	remaining: 3.26s
92:	learn: 0.0305608	total: 334ms	remaining: 3.25s
93:	learn: 0.0302281	total: 337ms	remaining: 3.25s
94:	learn: 0.0292530	total: 340ms	remaining: 3.24s
95:	learn: 0.0288806	total: 343ms	remaining: 3.23s
96:	learn: 0.0284506	total: 346ms	remaining: 3.22s
97:	learn: 0.0278446	total: 349ms	remaining: 3.21s
98:	learn: 0.0277692	total: 352ms	remaining: 3.2s
99:	learn: 0.0273034	total: 354ms	remaining: 3.19s
100:	learn: 0.0269761	total: 357ms	remaining: 3.18s
101:	learn: 0.0266045	total: 360ms	remaining: 3.17s
102:	learn: 0.0264139	total: 364ms	remaining: 3.17s
103:	learn: 0.0259257	total: 366ms	remaining: 3.16s
104:	learn: 0.0252155	total: 369ms	remaining: 3.15s
105:	learn: 0.0249033	total: 373ms	remaining: 3.14s
106:	learn: 0.0245009	total: 376ms	remaining: 3.14s
107:	learn: 0.0242699	total: 379ms	remaining: 3.13s
108:	learn: 0.0239662	total: 382ms	remaining: 3.12s
109:	learn: 0.0237389	total: 385ms	remaining: 3.11s
110:	learn: 0.0233399	total: 387ms	remaining: 3.1s
111:	learn: 0.0229714	total: 390ms	remaining: 3.09s
112:	learn: 0.0226283	total: 393ms	remaining: 3.08s
113:	learn: 0.0223256	total: 396ms	remaining: 3.08s
114:	learn: 0.0220176	total: 399ms	remaining: 3.07s
115:	learn: 0.0218053	total: 401ms	remaining: 3.06s
116:	learn: 0.0215717	total: 406ms	remaining: 3.07s
117:	learn: 0.0212424	total: 411ms	remaining: 3.08s
118:	learn: 0.0210145	total: 421ms	remaining: 3.11s
119:	learn: 0.0209611	total: 426ms	remaining: 3.12s
120:	learn: 0.0206972	total: 431ms	remaining: 3.13s
121:	learn: 0.0204434	total: 443ms	remaining: 3.19s
122:	learn: 0.0199888	total: 452ms	remaining: 3.23s
123:	learn: 0.0198495	total: 457ms	remaining: 3.23s
124:	learn: 0.0195335	total: 462ms	remaining: 3.24s
125:	learn: 0.0194897	total: 468ms	remaining: 3.24s
126:	learn: 0.0192646	total: 472ms	remaining: 3.25s
127:	learn: 0.0188642	total: 478ms	remaining: 3.26s
128:	learn: 0.0185898	total: 484ms	remaining: 3.27s
129:	learn: 0.0184807	total: 489ms	remaining: 3.27s
130:	learn: 0.0182630	total: 491ms	remaining: 3.26s
131:	learn: 0.0181032	total: 495ms	remaining: 3.25s
132:	learn: 0.0178470	total: 498ms	remaining: 3.24s
133:	learn: 0.0178202	total: 500ms	remaining: 3.23s
134:	learn: 0.0177946	total: 503ms	remaining: 3.22s
135:	learn: 0.0175786	total: 506ms	remaining: 3.22s
136:	learn: 0.0173990	total: 509ms	remaining: 3.21s
137:	learn: 0.0171470	total: 512ms	remaining: 3.2s
138:	learn: 0.0170032	total: 516ms	remaining: 3.2s
139:	learn: 0.0167866	total: 519ms	remaining: 3.19s
140:	learn: 0.0164166	total: 522ms	remaining: 3.18s
141:	learn: 0.0161070	total: 526ms	remaining: 3.18s
142:	learn: 0.0159363	total: 528ms	remaining: 3.17s
143:	learn: 0.0156765	total: 531ms	remaining: 3.16s
144:	learn: 0.0155693	total: 534ms	remaining: 3.15s
145:	learn: 0.0154489	total: 537ms	remaining: 3.14s
146:	learn: 0.0152002	total: 541ms	remaining: 3.14s
147:	learn: 0.0151054	total: 544ms	remaining: 3.13s
148:	learn: 0.0149623	total: 548ms	remaining: 3.13s
149:	learn: 0.0147375	total: 553ms	remaining: 3.13s
150:	learn: 0.0145934	total: 556ms	remaining: 3.13s
151:	learn: 0.0144452	total: 559ms	remaining: 3.12s
152:	learn: 0.0142262	total: 562ms	remaining: 3.11s
153:	learn: 0.0141076	total: 564ms	remaining: 3.1s
154:	learn: 0.0139565	total: 566ms	remaining: 3.09s
155:	learn: 0.0136784	total: 569ms	remaining: 3.08s
156:	learn: 0.0135029	total: 571ms	remaining: 3.07s
157:	learn: 0.0133552	total: 574ms	remaining: 3.06s
158:	learn: 0.0132870	total: 577ms	remaining: 3.05s
159:	learn: 0.0131621	total: 580ms	remaining: 3.05s
160:	learn: 0.0130014	total: 584ms	remaining: 3.04s
161:	learn: 0.0129210	total: 587ms	remaining: 3.04s
162:	learn: 0.0128593	total: 590ms	remaining: 3.03s
163:	learn: 0.0127841	total: 593ms	remaining: 3.02s
164:	learn: 0.0127087	total: 597ms	remaining: 3.02s
165:	learn: 0.0126453	total: 600ms	remaining: 3.02s
166:	learn: 0.0126357	total: 604ms	remaining: 3.01s
167:	learn: 0.0125270	total: 608ms	remaining: 3.01s
168:	learn: 0.0123779	total: 611ms	remaining: 3s
169:	learn: 0.0123286	total: 615ms	remaining: 3s
170:	learn: 0.0122973	total: 618ms	remaining: 3s
171:	learn: 0.0122813	total: 621ms	remaining: 2.99s
172:	learn: 0.0122033	total: 624ms	remaining: 2.98s
173:	learn: 0.0121156	total: 628ms	remaining: 2.98s
174:	learn: 0.0120623	total: 630ms	remaining: 2.97s
175:	learn: 0.0120362	total: 633ms	remaining: 2.96s
176:	learn: 0.0119401	total: 638ms	remaining: 2.96s
177:	learn: 0.0118102	total: 641ms	remaining: 2.96s
178:	learn: 0.0116930	total: 644ms	remaining: 2.95s
179:	learn: 0.0115939	total: 648ms	remaining: 2.95s
180:	learn: 0.0115463	total: 650ms	remaining: 2.94s
181:	learn: 0.0115340	total: 653ms	remaining: 2.93s
182:	learn: 0.0115170	total: 655ms	remaining: 2.92s
183:	learn: 0.0115168	total: 657ms	remaining: 2.92s
184:	learn: 0.0114706	total: 661ms	remaining: 2.91s
185:	learn: 0.0114588	total: 665ms	remaining: 2.91s
186:	learn: 0.0114480	total: 668ms	remaining: 2.9s
187:	learn: 0.0113402	total: 671ms	remaining: 2.9s
188:	learn: 0.0112723	total: 673ms	remaining: 2.89s
189:	learn: 0.0112205	total: 677ms	remaining: 2.88s
190:	learn: 0.0111880	total: 680ms	remaining: 2.88s
191:	learn: 0.0110370	total: 684ms	remaining: 2.88s
192:	learn: 0.0110115	total: 687ms	remaining: 2.87s
193:	learn: 0.0109314	total: 690ms	remaining: 2.87s
194:	learn: 0.0108165	total: 692ms	remaining: 2.86s
195:	learn: 0.0107355	total: 696ms	remaining: 2.85s
196:	learn: 0.0107215	total: 699ms	remaining: 2.85s
197:	learn: 0.0107008	total: 703ms	remaining: 2.85s
198:	learn: 0.0106637	total: 706ms	remaining: 2.84s
199:	learn: 0.0105982	total: 709ms	remaining: 2.84s
200:	learn: 0.0105326	total: 712ms	remaining: 2.83s
201:	learn: 0.0104610	total: 716ms	remaining: 2.83s
202:	learn: 0.0103801	total: 719ms	remaining: 2.82s
203:	learn: 0.0103058	total: 722ms	remaining: 2.82s
204:	learn: 0.0102664	total: 724ms	remaining: 2.81s
205:	learn: 0.0101012	total: 728ms	remaining: 2.8s
206:	learn: 0.0100297	total: 731ms	remaining: 2.8s
207:	learn: 0.0099948	total: 733ms	remaining: 2.79s
208:	learn: 0.0099648	total: 735ms	remaining: 2.78s
209:	learn: 0.0099334	total: 738ms	remaining: 2.77s
210:	learn: 0.0098731	total: 740ms	remaining: 2.77s
211:	learn: 0.0098681	total: 745ms	remaining: 2.77s
212:	learn: 0.0098595	total: 750ms	remaining: 2.77s
213:	learn: 0.0098236	total: 755ms	remaining: 2.77s
214:	learn: 0.0097836	total: 760ms	remaining: 2.77s
215:	learn: 0.0097711	total: 764ms	remaining: 2.77s
216:	learn: 0.0097396	total: 769ms	remaining: 2.78s
217:	learn: 0.0096574	total: 774ms	remaining: 2.78s
218:	learn: 0.0095799	total: 779ms	remaining: 2.78s
219:	learn: 0.0095431	total: 784ms	remaining: 2.78s
220:	learn: 0.0094941	total: 791ms	remaining: 2.79s
221:	learn: 0.0094124	total: 796ms	remaining: 2.79s
222:	learn: 0.0093853	total: 803ms	remaining: 2.8s
223:	learn: 0.0092791	total: 815ms	remaining: 2.82s
224:	learn: 0.0092752	total: 821ms	remaining: 2.83s
225:	learn: 0.0092701	total: 824ms	remaining: 2.82s
226:	learn: 0.0092107	total: 830ms	remaining: 2.83s
227:	learn: 0.0091500	total: 833ms	remaining: 2.82s
228:	learn: 0.0091052	total: 835ms	remaining: 2.81s
229:	learn: 0.0090173	total: 839ms	remaining: 2.81s
230:	learn: 0.0089622	total: 842ms	remaining: 2.8s
231:	learn: 0.0089207	total: 845ms	remaining: 2.8s
232:	learn: 0.0088958	total: 848ms	remaining: 2.79s
233:	learn: 0.0088296	total: 851ms	remaining: 2.79s
234:	learn: 0.0087634	total: 854ms	remaining: 2.78s
235:	learn: 0.0087375	total: 857ms	remaining: 2.77s
236:	learn: 0.0086957	total: 860ms	remaining: 2.77s
237:	learn: 0.0086174	total: 863ms	remaining: 2.76s
238:	learn: 0.0085792	total: 867ms	remaining: 2.76s
239:	learn: 0.0085329	total: 870ms	remaining: 2.75s
240:	learn: 0.0084744	total: 874ms	remaining: 2.75s
241:	learn: 0.0084052	total: 878ms	remaining: 2.75s
242:	learn: 0.0083976	total: 880ms	remaining: 2.74s
243:	learn: 0.0083461	total: 883ms	remaining: 2.74s
244:	learn: 0.0082745	total: 887ms	remaining: 2.73s
245:	learn: 0.0082005	total: 891ms	remaining: 2.73s
246:	learn: 0.0081797	total: 895ms	remaining: 2.73s
247:	learn: 0.0081274	total: 898ms	remaining: 2.72s
248:	learn: 0.0081273	total: 901ms	remaining: 2.72s
249:	learn: 0.0080888	total: 904ms	remaining: 2.71s
250:	learn: 0.0080470	total: 908ms	remaining: 2.71s
251:	learn: 0.0080053	total: 911ms	remaining: 2.7s
252:	learn: 0.0079811	total: 915ms	remaining: 2.7s
253:	learn: 0.0079089	total: 917ms	remaining: 2.69s
254:	learn: 0.0078050	total: 921ms	remaining: 2.69s
255:	learn: 0.0077768	total: 925ms	remaining: 2.69s
256:	learn: 0.0077383	total: 929ms	remaining: 2.69s
257:	learn: 0.0076814	total: 932ms	remaining: 2.68s
258:	learn: 0.0076216	total: 935ms	remaining: 2.67s
259:	learn: 0.0075735	total: 938ms	remaining: 2.67s
260:	learn: 0.0075224	total: 940ms	remaining: 2.66s
261:	learn: 0.0074897	total: 943ms	remaining: 2.65s
262:	learn: 0.0074431	total: 945ms	remaining: 2.65s
263:	learn: 0.0074094	total: 948ms	remaining: 2.64s
264:	learn: 0.0073880	total: 952ms	remaining: 2.64s
265:	learn: 0.0073766	total: 955ms	remaining: 2.64s
266:	learn: 0.0073370	total: 958ms	remaining: 2.63s
267:	learn: 0.0072881	total: 960ms	remaining: 2.62s
268:	learn: 0.0072426	total: 963ms	remaining: 2.62s
269:	learn: 0.0071907	total: 965ms	remaining: 2.61s
270:	learn: 0.0071442	total: 968ms	remaining: 2.6s
271:	learn: 0.0070998	total: 971ms	remaining: 2.6s
272:	learn: 0.0070483	total: 973ms	remaining: 2.59s
273:	learn: 0.0069983	total: 976ms	remaining: 2.59s
274:	learn: 0.0069542	total: 979ms	remaining: 2.58s
275:	learn: 0.0069140	total: 982ms	remaining: 2.57s
276:	learn: 0.0068567	total: 985ms	remaining: 2.57s
277:	learn: 0.0068319	total: 987ms	remaining: 2.56s
278:	learn: 0.0067848	total: 991ms	remaining: 2.56s
279:	learn: 0.0067353	total: 996ms	remaining: 2.56s
280:	learn: 0.0067197	total: 1s	remaining: 2.56s
281:	learn: 0.0067176	total: 1.01s	remaining: 2.56s
282:	learn: 0.0067176	total: 1.01s	remaining: 2.56s
283:	learn: 0.0067004	total: 1.02s	remaining: 2.58s
284:	learn: 0.0066704	total: 1.03s	remaining: 2.57s
285:	learn: 0.0066180	total: 1.03s	remaining: 2.57s
286:	learn: 0.0065800	total: 1.03s	remaining: 2.57s
287:	learn: 0.0065440	total: 1.04s	remaining: 2.57s
288:	learn: 0.0064784	total: 1.05s	remaining: 2.59s
289:	learn: 0.0064230	total: 1.07s	remaining: 2.61s
290:	learn: 0.0064231	total: 1.07s	remaining: 2.62s
291:	learn: 0.0063912	total: 1.08s	remaining: 2.62s
292:	learn: 0.0063265	total: 1.08s	remaining: 2.62s
293:	learn: 0.0063115	total: 1.09s	remaining: 2.61s
294:	learn: 0.0062861	total: 1.09s	remaining: 2.6s
295:	learn: 0.0062857	total: 1.09s	remaining: 2.6s
296:	learn: 0.0062396	total: 1.09s	remaining: 2.59s
297:	learn: 0.0062021	total: 1.1s	remaining: 2.59s
298:	learn: 0.0061431	total: 1.1s	remaining: 2.59s
299:	learn: 0.0061123	total: 1.11s	remaining: 2.58s
300:	learn: 0.0061122	total: 1.11s	remaining: 2.58s
301:	learn: 0.0061121	total: 1.11s	remaining: 2.57s
302:	learn: 0.0061069	total: 1.11s	remaining: 2.57s
303:	learn: 0.0060853	total: 1.12s	remaining: 2.56s
304:	learn: 0.0060469	total: 1.12s	remaining: 2.56s
305:	learn: 0.0060284	total: 1.13s	remaining: 2.55s
306:	learn: 0.0060284	total: 1.13s	remaining: 2.54s
307:	learn: 0.0060018	total: 1.13s	remaining: 2.54s
308:	learn: 0.0059881	total: 1.13s	remaining: 2.53s
309:	learn: 0.0059648	total: 1.14s	remaining: 2.53s
310:	learn: 0.0059501	total: 1.14s	remaining: 2.52s
311:	learn: 0.0059402	total: 1.14s	remaining: 2.52s
312:	learn: 0.0059402	total: 1.15s	remaining: 2.51s
313:	learn: 0.0059162	total: 1.15s	remaining: 2.51s
314:	learn: 0.0059124	total: 1.15s	remaining: 2.5s
315:	learn: 0.0058822	total: 1.16s	remaining: 2.5s
316:	learn: 0.0058537	total: 1.16s	remaining: 2.5s
317:	learn: 0.0058092	total: 1.16s	remaining: 2.49s
318:	learn: 0.0057734	total: 1.16s	remaining: 2.49s
319:	learn: 0.0057463	total: 1.17s	remaining: 2.48s
320:	learn: 0.0057194	total: 1.17s	remaining: 2.48s
321:	learn: 0.0056970	total: 1.17s	remaining: 2.47s
322:	learn: 0.0056739	total: 1.18s	remaining: 2.47s
323:	learn: 0.0056645	total: 1.18s	remaining: 2.46s
324:	learn: 0.0056315	total: 1.18s	remaining: 2.46s
325:	learn: 0.0056313	total: 1.19s	remaining: 2.45s
326:	learn: 0.0056028	total: 1.19s	remaining: 2.44s
327:	learn: 0.0055982	total: 1.19s	remaining: 2.44s
328:	learn: 0.0055610	total: 1.19s	remaining: 2.44s
329:	learn: 0.0055472	total: 1.2s	remaining: 2.43s
330:	learn: 0.0055290	total: 1.2s	remaining: 2.42s
331:	learn: 0.0055088	total: 1.2s	remaining: 2.42s
332:	learn: 0.0055037	total: 1.21s	remaining: 2.41s
333:	learn: 0.0055037	total: 1.21s	remaining: 2.41s
334:	learn: 0.0054922	total: 1.21s	remaining: 2.4s
335:	learn: 0.0054694	total: 1.21s	remaining: 2.39s
336:	learn: 0.0054595	total: 1.21s	remaining: 2.39s
337:	learn: 0.0054594	total: 1.22s	remaining: 2.39s
338:	learn: 0.0054594	total: 1.22s	remaining: 2.38s
339:	learn: 0.0054288	total: 1.23s	remaining: 2.38s
340:	learn: 0.0054038	total: 1.23s	remaining: 2.38s
341:	learn: 0.0054037	total: 1.24s	remaining: 2.38s
342:	learn: 0.0053904	total: 1.24s	remaining: 2.38s
343:	learn: 0.0053899	total: 1.25s	remaining: 2.38s
344:	learn: 0.0053545	total: 1.25s	remaining: 2.38s
345:	learn: 0.0053348	total: 1.26s	remaining: 2.38s
346:	learn: 0.0053347	total: 1.26s	remaining: 2.38s
347:	learn: 0.0053145	total: 1.27s	remaining: 2.37s
348:	learn: 0.0052988	total: 1.27s	remaining: 2.37s
349:	learn: 0.0052845	total: 1.28s	remaining: 2.37s
350:	learn: 0.0052845	total: 1.28s	remaining: 2.37s
351:	learn: 0.0052605	total: 1.29s	remaining: 2.37s
352:	learn: 0.0052455	total: 1.29s	remaining: 2.37s
353:	learn: 0.0052454	total: 1.29s	remaining: 2.36s
354:	learn: 0.0052454	total: 1.3s	remaining: 2.36s
355:	learn: 0.0052144	total: 1.3s	remaining: 2.35s
356:	learn: 0.0051857	total: 1.3s	remaining: 2.35s
357:	learn: 0.0051670	total: 1.31s	remaining: 2.35s
358:	learn: 0.0051525	total: 1.31s	remaining: 2.34s
359:	learn: 0.0051524	total: 1.31s	remaining: 2.33s
360:	learn: 0.0051290	total: 1.31s	remaining: 2.33s
361:	learn: 0.0051148	total: 1.32s	remaining: 2.32s
362:	learn: 0.0051056	total: 1.32s	remaining: 2.32s
363:	learn: 0.0051055	total: 1.32s	remaining: 2.31s
364:	learn: 0.0050755	total: 1.32s	remaining: 2.31s
365:	learn: 0.0050755	total: 1.33s	remaining: 2.3s
366:	learn: 0.0050589	total: 1.33s	remaining: 2.29s
367:	learn: 0.0050406	total: 1.33s	remaining: 2.29s
368:	learn: 0.0049975	total: 1.33s	remaining: 2.28s
369:	learn: 0.0049716	total: 1.34s	remaining: 2.28s
370:	learn: 0.0049499	total: 1.34s	remaining: 2.27s
371:	learn: 0.0049270	total: 1.34s	remaining: 2.27s
372:	learn: 0.0049106	total: 1.35s	remaining: 2.26s
373:	learn: 0.0048886	total: 1.35s	remaining: 2.26s
374:	learn: 0.0048886	total: 1.35s	remaining: 2.25s
375:	learn: 0.0048886	total: 1.35s	remaining: 2.25s
376:	learn: 0.0048406	total: 1.36s	remaining: 2.24s
377:	learn: 0.0048202	total: 1.36s	remaining: 2.24s
378:	learn: 0.0047954	total: 1.36s	remaining: 2.23s
379:	learn: 0.0047633	total: 1.37s	remaining: 2.23s
380:	learn: 0.0047481	total: 1.37s	remaining: 2.23s
381:	learn: 0.0047114	total: 1.38s	remaining: 2.23s
382:	learn: 0.0047109	total: 1.38s	remaining: 2.22s
383:	learn: 0.0046988	total: 1.38s	remaining: 2.22s
384:	learn: 0.0046673	total: 1.38s	remaining: 2.21s
385:	learn: 0.0046472	total: 1.39s	remaining: 2.21s
386:	learn: 0.0046271	total: 1.39s	remaining: 2.2s

In [217]:
# Evaluate models
for info in models:
    accuracy,precision,recall,f1=evaluate_model_on_test_data(info["model"])
    info['accuracy']=accuracy
    info["precision"] = precision
    info["recall"] = recall
    info["f1"] = f1
    
# report
df_evaluation_report_test = pd.DataFrame(models, columns=["name", "accuracy", "precision", "recall", "f1"])
df_evaluation_report_test

                  name accuracy precision recall    f1
0  Logistic Regression     0.79      0.78   0.79  0.78
1                  KNN     0.62      0.60   0.60  0.60
2                  SVM     0.69      0.68   0.65  0.65
3        Decision Tree     0.62      0.62   0.62  0.62
4        Random Forest     0.85      0.84   0.85  0.85
5             AdaBoost     0.82      0.81   0.81  0.81
6             CatBoost     0.82      0.81   0.81  0.81